/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_frenet_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* f1tenth_frenet_expl_ode_fun:(i0[6],i1[2],i2)->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, *w09=w+14, w10;
  casadi_real w11, w12, w13, w14;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[3] */
  for (rr=(&w01), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #2: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: @5 = @0[4] */
  for (rr=(&w05), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #6: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #7: @6 = (@5*@2) */
  w06  = (w05*w02);
  /* #8: @4 = (@4-@6) */
  w04 -= w06;
  /* #9: @6 = 1 */
  w06 = 1.;
  /* #10: @7 = @0[1] */
  for (rr=(&w07), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #11: @8 = input[2][0] */
  w08 = arg[2] ? arg[2][0] : 0;
  /* #12: @7 = (@7*@8) */
  w07 *= w08;
  /* #13: @6 = (@6-@7) */
  w06 -= w07;
  /* #14: @7 = 1e-06 */
  w07 = 9.9999999999999995e-07;
  /* #15: @6 = fmax(@6,@7) */
  w06  = casadi_fmax(w06,w07);
  /* #16: @4 = (@4/@6) */
  w04 /= w06;
  /* #17: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #18: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #19: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #20: @2 = (@2+@3) */
  w02 += w03;
  /* #21: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #22: @2 = @0[5] */
  for (rr=(&w02), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #23: @8 = (@8*@4) */
  w08 *= w04;
  /* #24: @8 = (@2-@8) */
  w08  = (w02-w08);
  /* #25: output[0][2] = @8 */
  if (res[0]) res[0][2] = w08;
  /* #26: @8 = 20 */
  w08 = 20.;
  /* #27: @9 = input[1][0] */
  casadi_copy(arg[1], 2, w09);
  /* #28: @4 = @9[0] */
  for (rr=(&w04), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #29: @8 = (@8*@4) */
  w08 *= w04;
  /* #30: @4 = 0.05 */
  w04 = 5.0000000000000003e-02;
  /* #31: @8 = (@8-@4) */
  w08 -= w04;
  /* #32: @4 = 134.585 */
  w04 = 1.3458500000000001e+02;
  /* #33: @3 = 1.2 */
  w03 = 1.2000000000000000e+00;
  /* #34: @6 = 9.242 */
  w06 = 9.2420000000000009e+00;
  /* #35: @7 = @9[1] */
  for (rr=(&w07), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #36: @10 = 0.15875 */
  w10 = 1.5875000000000000e-01;
  /* #37: @11 = (@10*@2) */
  w11  = (w10*w02);
  /* #38: @11 = (@5+@11) */
  w11  = (w05+w11);
  /* #39: @12 = 0.001 */
  w12 = 1.0000000000000000e-03;
  /* #40: @12 = fmax(@1,@12) */
  w12  = casadi_fmax(w01,w12);
  /* #41: @11 = atan2(@11,@12) */
  w11  = atan2(w11,w12);
  /* #42: @11 = (@7-@11) */
  w11  = (w07-w11);
  /* #43: @6 = (@6*@11) */
  w06 *= w11;
  /* #44: @6 = atan(@6) */
  w06 = atan( w06 );
  /* #45: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #46: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #47: @4 = (@4*@6) */
  w04 *= w06;
  /* #48: @6 = sin(@7) */
  w06 = sin( w07 );
  /* #49: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #50: @8 = (@8-@6) */
  w08 -= w06;
  /* #51: @6 = 3.47 */
  w06 = 3.4700000000000002e+00;
  /* #52: @11 = (@6*@5) */
  w11  = (w06*w05);
  /* #53: @11 = (@11*@2) */
  w11 *= w02;
  /* #54: @8 = (@8+@11) */
  w08 += w11;
  /* #55: @8 = (@8/@6) */
  w08 /= w06;
  /* #56: output[0][3] = @8 */
  if (res[0]) res[0][3] = w08;
  /* #57: @8 = 159.919 */
  w08 = 1.5991900000000001e+02;
  /* #58: @11 = 17.716 */
  w11 = 1.7716000000000001e+01;
  /* #59: @13 = 0.17145 */
  w13 = 1.7144999999999999e-01;
  /* #60: @14 = (@13*@2) */
  w14  = (w13*w02);
  /* #61: @5 = (@5-@14) */
  w05 -= w14;
  /* #62: @5 = atan2(@5,@12) */
  w05  = atan2(w05,w12);
  /* #63: @11 = (@11*@5) */
  w11 *= w05;
  /* #64: @11 = (-@11) */
  w11 = (- w11 );
  /* #65: @11 = atan(@11) */
  w11 = atan( w11 );
  /* #66: @3 = (@3*@11) */
  w03 *= w11;
  /* #67: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #68: @8 = (@8*@3) */
  w08 *= w03;
  /* #69: @7 = cos(@7) */
  w07 = cos( w07 );
  /* #70: @3 = (@4*@7) */
  w03  = (w04*w07);
  /* #71: @3 = (@8+@3) */
  w03  = (w08+w03);
  /* #72: @1 = (@6*@1) */
  w01  = (w06*w01);
  /* #73: @1 = (@1*@2) */
  w01 *= w02;
  /* #74: @3 = (@3-@1) */
  w03 -= w01;
  /* #75: @3 = (@3/@6) */
  w03 /= w06;
  /* #76: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #77: @10 = (@10*@4) */
  w10 *= w04;
  /* #78: @10 = (@10*@7) */
  w10 *= w07;
  /* #79: @13 = (@13*@8) */
  w13 *= w08;
  /* #80: @10 = (@10-@13) */
  w10 -= w13;
  /* #81: @13 = 0.04712 */
  w13 = 4.7120000000000002e-02;
  /* #82: @10 = (@10/@13) */
  w10 /= w13;
  /* #83: output[0][5] = @10 */
  if (res[0]) res[0][5] = w10;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_frenet_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 21;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 21*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
