/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_frenet_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};

/* f1tenth_frenet_expl_vde_adj:(i0[6],i1[6],i2[2],i3)->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w01, *w02=w+7, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+28, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, *w27=w+42, w28, w29, w30, w31, w32, w33, w34;
  casadi_real w35;
  const casadi_real *cs;
  /* #0: @0 = zeros(6x1) */
  casadi_clear(w00, 6);
  /* #1: @1 = 0.17145 */
  w01 = 1.7144999999999999e-01;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 6, w02);
  /* #3: @3 = @2[3] */
  for (rr=(&w03), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #4: @4 = 0.001 */
  w04 = 1.0000000000000000e-03;
  /* #5: @5 = fmax(@3,@4) */
  w05  = casadi_fmax(w03,w04);
  /* #6: @6 = @2[4] */
  for (rr=(&w06), cs=w02+4; cs!=w02+5; cs+=1) *rr++ = *cs;
  /* #7: @7 = @2[5] */
  for (rr=(&w07), cs=w02+5; cs!=w02+6; cs+=1) *rr++ = *cs;
  /* #8: @8 = (@1*@7) */
  w08  = (w01*w07);
  /* #9: @8 = (@6-@8) */
  w08  = (w06-w08);
  /* #10: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #11: @10 = sq(@5) */
  w10 = casadi_sq( w05 );
  /* #12: @9 = (@9+@10) */
  w09 += w10;
  /* #13: @11 = (@5/@9) */
  w11  = (w05/w09);
  /* #14: @12 = 17.716 */
  w12 = 1.7716000000000001e+01;
  /* #15: @13 = 1.2 */
  w13 = 1.2000000000000000e+00;
  /* #16: @14 = atan2(@8,@5) */
  w14  = atan2(w08,w05);
  /* #17: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #18: @15 = (-@14) */
  w15 = (- w14 );
  /* #19: @15 = atan(@15) */
  w15 = atan( w15 );
  /* #20: @15 = (@13*@15) */
  w15  = (w13*w15);
  /* #21: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #22: @16 = 159.919 */
  w16 = 1.5991900000000001e+02;
  /* #23: @17 = 0.288184 */
  w17 = 2.8818443804034583e-01;
  /* #24: @18 = input[1][0] */
  casadi_copy(arg[1], 6, w18);
  /* #25: {@19, @20, @21, @22, @23, @24} = vertsplit(@18) */
  w19 = w18[0];
  w20 = w18[1];
  w21 = w18[2];
  w22 = w18[3];
  w23 = w18[4];
  w24 = w18[5];
  /* #26: @23 = (@17*@23) */
  w23  = (w17*w23);
  /* #27: @25 = 21.2224 */
  w25 = 2.1222410865874362e+01;
  /* #28: @25 = (@25*@24) */
  w25 *= w24;
  /* #29: @24 = (@1*@25) */
  w24  = (w01*w25);
  /* #30: @24 = (@23-@24) */
  w24  = (w23-w24);
  /* #31: @16 = (@16*@24) */
  w16 *= w24;
  /* #32: @15 = (@15*@16) */
  w15 *= w16;
  /* #33: @15 = (@13*@15) */
  w15  = (w13*w15);
  /* #34: @16 = 1 */
  w16 = 1.;
  /* #35: @14 = sq(@14) */
  w14 = casadi_sq( w14 );
  /* #36: @14 = (@16+@14) */
  w14  = (w16+w14);
  /* #37: @15 = (@15/@14) */
  w15 /= w14;
  /* #38: @12 = (@12*@15) */
  w12 *= w15;
  /* #39: @11 = (@11*@12) */
  w11 *= w12;
  /* #40: @1 = (@1*@11) */
  w01 *= w11;
  /* #41: @15 = 3.47 */
  w15 = 3.4700000000000002e+00;
  /* #42: @14 = (@15*@3) */
  w14  = (w15*w03);
  /* #43: @14 = (@14*@23) */
  w14 *= w23;
  /* #44: @1 = (@1-@14) */
  w01 -= w14;
  /* #45: @14 = (@15*@6) */
  w14  = (w15*w06);
  /* #46: @17 = (@17*@22) */
  w17 *= w22;
  /* #47: @14 = (@14*@17) */
  w14 *= w17;
  /* #48: @1 = (@1+@14) */
  w01 += w14;
  /* #49: @14 = 0.15875 */
  w14 = 1.5875000000000000e-01;
  /* #50: @22 = (@14*@7) */
  w22  = (w14*w07);
  /* #51: @22 = (@6+@22) */
  w22  = (w06+w22);
  /* #52: @24 = sq(@22) */
  w24 = casadi_sq( w22 );
  /* #53: @24 = (@24+@10) */
  w24 += w10;
  /* #54: @10 = (@5/@24) */
  w10  = (w05/w24);
  /* #55: @26 = 9.242 */
  w26 = 9.2420000000000009e+00;
  /* #56: @27 = input[2][0] */
  casadi_copy(arg[2], 2, w27);
  /* #57: @28 = @27[1] */
  for (rr=(&w28), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #58: @5 = atan2(@22,@5) */
  w05  = atan2(w22,w05);
  /* #59: @5 = (@28-@5) */
  w05  = (w28-w05);
  /* #60: @5 = (@26*@5) */
  w05  = (w26*w05);
  /* #61: @29 = atan(@5) */
  w29 = atan( w05 );
  /* #62: @29 = (@13*@29) */
  w29  = (w13*w29);
  /* #63: @30 = cos(@29) */
  w30 = cos( w29 );
  /* #64: @31 = 134.585 */
  w31 = 1.3458500000000001e+02;
  /* #65: @32 = cos(@28) */
  w32 = cos( w28 );
  /* #66: @33 = (@32*@25) */
  w33  = (w32*w25);
  /* #67: @33 = (@14*@33) */
  w33  = (w14*w33);
  /* #68: @34 = (@32*@23) */
  w34  = (w32*w23);
  /* #69: @33 = (@33+@34) */
  w33 += w34;
  /* #70: @28 = sin(@28) */
  w28 = sin( w28 );
  /* #71: @34 = (@28*@17) */
  w34  = (w28*w17);
  /* #72: @33 = (@33-@34) */
  w33 -= w34;
  /* #73: @33 = (@31*@33) */
  w33  = (w31*w33);
  /* #74: @30 = (@30*@33) */
  w30 *= w33;
  /* #75: @13 = (@13*@30) */
  w13 *= w30;
  /* #76: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #77: @5 = (@16+@5) */
  w05  = (w16+w05);
  /* #78: @13 = (@13/@5) */
  w13 /= w05;
  /* #79: @26 = (@26*@13) */
  w26 *= w13;
  /* #80: @10 = (@10*@26) */
  w10 *= w26;
  /* #81: @13 = (@14*@10) */
  w13  = (w14*w10);
  /* #82: @1 = (@1-@13) */
  w01 -= w13;
  /* #83: @1 = (@1+@21) */
  w01 += w21;
  /* #84: (@0[5] += @1) */
  for (rr=w00+5, cs=(&w01); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #85: @1 = input[3][0] */
  w01 = arg[3] ? arg[3][0] : 0;
  /* #86: @13 = 1e-06 */
  w13 = 9.9999999999999995e-07;
  /* #87: @5 = @2[1] */
  for (rr=(&w05), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #88: @5 = (@5*@1) */
  w05 *= w01;
  /* #89: @16 = (@16-@5) */
  w16 -= w05;
  /* #90: @5 = (@13<=@16) */
  w05  = (w13<=w16);
  /* #91: @30 = (@16<=@13) */
  w30  = (w16<=w13);
  /* #92: @30 = (@5+@30) */
  w30  = (w05+w30);
  /* #93: @5 = (@5/@30) */
  w05 /= w30;
  /* #94: @30 = @2[2] */
  for (rr=(&w30), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #95: @33 = cos(@30) */
  w33 = cos( w30 );
  /* #96: @34 = (@3*@33) */
  w34  = (w03*w33);
  /* #97: @30 = sin(@30) */
  w30 = sin( w30 );
  /* #98: @35 = (@6*@30) */
  w35  = (w06*w30);
  /* #99: @34 = (@34-@35) */
  w34 -= w35;
  /* #100: @16 = fmax(@16,@13) */
  w16  = casadi_fmax(w16,w13);
  /* #101: @34 = (@34/@16) */
  w34 /= w16;
  /* #102: @34 = (@34/@16) */
  w34 /= w16;
  /* #103: @21 = (@1*@21) */
  w21  = (w01*w21);
  /* #104: @19 = (@19-@21) */
  w19 -= w21;
  /* #105: @34 = (@34*@19) */
  w34 *= w19;
  /* #106: @5 = (@5*@34) */
  w05 *= w34;
  /* #107: @1 = (@1*@5) */
  w01 *= w05;
  /* #108: (@0[1] += @1) */
  for (rr=w00+1, cs=(&w01); rr!=w00+2; rr+=1) *rr += *cs++;
  /* #109: @1 = (@7*@17) */
  w01  = (w07*w17);
  /* #110: @1 = (@15*@1) */
  w01  = (w15*w01);
  /* #111: @1 = (@1-@11) */
  w01 -= w11;
  /* #112: @1 = (@1-@10) */
  w01 -= w10;
  /* #113: @10 = (@33*@20) */
  w10  = (w33*w20);
  /* #114: @1 = (@1+@10) */
  w01 += w10;
  /* #115: @19 = (@19/@16) */
  w19 /= w16;
  /* #116: @16 = (@30*@19) */
  w16  = (w30*w19);
  /* #117: @1 = (@1-@16) */
  w01 -= w16;
  /* #118: (@0[4] += @1) */
  for (rr=w00+4, cs=(&w01); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #119: @1 = (@3*@20) */
  w01  = (w03*w20);
  /* #120: @1 = (@33*@1) */
  w01  = (w33*w01);
  /* #121: @16 = (@6*@20) */
  w16  = (w06*w20);
  /* #122: @16 = (@30*@16) */
  w16  = (w30*w16);
  /* #123: @1 = (@1-@16) */
  w01 -= w16;
  /* #124: @6 = (@6*@19) */
  w06 *= w19;
  /* #125: @6 = (@33*@6) */
  w06  = (w33*w06);
  /* #126: @1 = (@1-@6) */
  w01 -= w06;
  /* #127: @6 = (@3*@19) */
  w06  = (w03*w19);
  /* #128: @6 = (@30*@6) */
  w06  = (w30*w06);
  /* #129: @1 = (@1-@6) */
  w01 -= w06;
  /* #130: (@0[2] += @1) */
  for (rr=w00+2, cs=(&w01); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #131: @1 = (@4<=@3) */
  w01  = (w04<=w03);
  /* #132: @3 = (@3<=@4) */
  w03  = (w03<=w04);
  /* #133: @3 = (@1+@3) */
  w03  = (w01+w03);
  /* #134: @1 = (@1/@3) */
  w01 /= w03;
  /* #135: @8 = (@8/@9) */
  w08 /= w09;
  /* #136: @8 = (@8*@12) */
  w08 *= w12;
  /* #137: @22 = (@22/@24) */
  w22 /= w24;
  /* #138: @22 = (@22*@26) */
  w22 *= w26;
  /* #139: @8 = (@8+@22) */
  w08 += w22;
  /* #140: @1 = (@1*@8) */
  w01 *= w08;
  /* #141: @7 = (@7*@23) */
  w07 *= w23;
  /* #142: @15 = (@15*@7) */
  w15 *= w07;
  /* #143: @1 = (@1-@15) */
  w01 -= w15;
  /* #144: @30 = (@30*@20) */
  w30 *= w20;
  /* #145: @1 = (@1+@30) */
  w01 += w30;
  /* #146: @33 = (@33*@19) */
  w33 *= w19;
  /* #147: @1 = (@1+@33) */
  w01 += w33;
  /* #148: (@0[3] += @1) */
  for (rr=w00+3, cs=(&w01); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #149: output[0][0] = @0 */
  casadi_copy(w00, 6, res[0]);
  /* #150: @27 = zeros(2x1) */
  casadi_clear(w27, 2);
  /* #151: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #152: @31 = (@31*@29) */
  w31 *= w29;
  /* #153: @23 = (@31*@23) */
  w23  = (w31*w23);
  /* #154: @23 = (@28*@23) */
  w23  = (w28*w23);
  /* #155: @23 = (-@23) */
  w23 = (- w23 );
  /* #156: @14 = (@14*@31) */
  w14 *= w31;
  /* #157: @14 = (@14*@25) */
  w14 *= w25;
  /* #158: @28 = (@28*@14) */
  w28 *= w14;
  /* #159: @23 = (@23-@28) */
  w23 -= w28;
  /* #160: @31 = (@31*@17) */
  w31 *= w17;
  /* #161: @32 = (@32*@31) */
  w32 *= w31;
  /* #162: @23 = (@23-@32) */
  w23 -= w32;
  /* #163: @23 = (@23+@26) */
  w23 += w26;
  /* #164: (@27[1] += @23) */
  for (rr=w27+1, cs=(&w23); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #165: @23 = 20 */
  w23 = 20.;
  /* #166: @23 = (@23*@17) */
  w23 *= w17;
  /* #167: (@27[0] += @23) */
  for (rr=w27+0, cs=(&w23); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #168: output[0][1] = @27 */
  if (res[0]) casadi_copy(w27, 2, res[0]+6);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_frenet_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 52;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 52*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
