/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_frenet_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* f1tenth_frenet_dyn_disc_phi_fun:(i0[6],i1[2],i2)->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, *w12=w+17, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, *w28=w+34, *w29=w+40, w30, w31, w32, *w33=w+49;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = 0.00333333 */
  w01 = 3.3333333333333335e-03;
  /* #2: @2 = @0[3] */
  for (rr=(&w02), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #3: @3 = @0[2] */
  for (rr=(&w03), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #4: @4 = cos(@3) */
  w04 = cos( w03 );
  /* #5: @5 = (@2*@4) */
  w05  = (w02*w04);
  /* #6: @6 = @0[4] */
  for (rr=(&w06), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #7: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #8: @7 = (@6*@3) */
  w07  = (w06*w03);
  /* #9: @5 = (@5-@7) */
  w05 -= w07;
  /* #10: @7 = 1 */
  w07 = 1.;
  /* #11: @8 = @0[1] */
  for (rr=(&w08), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #12: @9 = input[2][0] */
  w09 = arg[2] ? arg[2][0] : 0;
  /* #13: @8 = (@8*@9) */
  w08 *= w09;
  /* #14: @8 = (@7-@8) */
  w08  = (w07-w08);
  /* #15: @10 = 1e-06 */
  w10 = 9.9999999999999995e-07;
  /* #16: @8 = fmax(@8,@10) */
  w08  = casadi_fmax(w08,w10);
  /* #17: @5 = (@5/@8) */
  w05 /= w08;
  /* #18: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #19: @4 = (@6*@4) */
  w04  = (w06*w04);
  /* #20: @3 = (@3+@4) */
  w03 += w04;
  /* #21: @4 = @0[5] */
  for (rr=(&w04), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #22: @8 = (@9*@5) */
  w08  = (w09*w05);
  /* #23: @8 = (@4-@8) */
  w08  = (w04-w08);
  /* #24: @11 = 20 */
  w11 = 20.;
  /* #25: @12 = input[1][0] */
  casadi_copy(arg[1], 2, w12);
  /* #26: @13 = @12[0] */
  for (rr=(&w13), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #27: @11 = (@11*@13) */
  w11 *= w13;
  /* #28: @13 = 0.05 */
  w13 = 5.0000000000000003e-02;
  /* #29: @11 = (@11-@13) */
  w11 -= w13;
  /* #30: @13 = 134.585 */
  w13 = 1.3458500000000001e+02;
  /* #31: @14 = 1.2 */
  w14 = 1.2000000000000000e+00;
  /* #32: @15 = 9.242 */
  w15 = 9.2420000000000009e+00;
  /* #33: @16 = @12[1] */
  for (rr=(&w16), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #34: @17 = 0.15875 */
  w17 = 1.5875000000000000e-01;
  /* #35: @18 = (@17*@4) */
  w18  = (w17*w04);
  /* #36: @18 = (@6+@18) */
  w18  = (w06+w18);
  /* #37: @19 = 0.001 */
  w19 = 1.0000000000000000e-03;
  /* #38: @20 = fmax(@2,@19) */
  w20  = casadi_fmax(w02,w19);
  /* #39: @18 = atan2(@18,@20) */
  w18  = atan2(w18,w20);
  /* #40: @18 = (@16-@18) */
  w18  = (w16-w18);
  /* #41: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #42: @18 = atan(@18) */
  w18 = atan( w18 );
  /* #43: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #44: @18 = sin(@18) */
  w18 = sin( w18 );
  /* #45: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #46: @21 = sin(@16) */
  w21 = sin( w16 );
  /* #47: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #48: @22 = (@11-@22) */
  w22  = (w11-w22);
  /* #49: @23 = 3.47 */
  w23 = 3.4700000000000002e+00;
  /* #50: @24 = (@23*@6) */
  w24  = (w23*w06);
  /* #51: @24 = (@24*@4) */
  w24 *= w04;
  /* #52: @22 = (@22+@24) */
  w22 += w24;
  /* #53: @22 = (@22/@23) */
  w22 /= w23;
  /* #54: @24 = 159.919 */
  w24 = 1.5991900000000001e+02;
  /* #55: @25 = 17.716 */
  w25 = 1.7716000000000001e+01;
  /* #56: @26 = 0.17145 */
  w26 = 1.7144999999999999e-01;
  /* #57: @27 = (@26*@4) */
  w27  = (w26*w04);
  /* #58: @6 = (@6-@27) */
  w06 -= w27;
  /* #59: @6 = atan2(@6,@20) */
  w06  = atan2(w06,w20);
  /* #60: @6 = (@25*@6) */
  w06  = (w25*w06);
  /* #61: @6 = (-@6) */
  w06 = (- w06 );
  /* #62: @6 = atan(@6) */
  w06 = atan( w06 );
  /* #63: @6 = (@14*@6) */
  w06  = (w14*w06);
  /* #64: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #65: @6 = (@24*@6) */
  w06  = (w24*w06);
  /* #66: @20 = cos(@16) */
  w20 = cos( w16 );
  /* #67: @27 = (@18*@20) */
  w27  = (w18*w20);
  /* #68: @27 = (@6+@27) */
  w27  = (w06+w27);
  /* #69: @2 = (@23*@2) */
  w02  = (w23*w02);
  /* #70: @2 = (@2*@4) */
  w02 *= w04;
  /* #71: @27 = (@27-@2) */
  w27 -= w02;
  /* #72: @27 = (@27/@23) */
  w27 /= w23;
  /* #73: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #74: @18 = (@18*@20) */
  w18 *= w20;
  /* #75: @6 = (@26*@6) */
  w06  = (w26*w06);
  /* #76: @18 = (@18-@6) */
  w18 -= w06;
  /* #77: @6 = 0.04712 */
  w06 = 4.7120000000000002e-02;
  /* #78: @18 = (@18/@6) */
  w18 /= w06;
  /* #79: @28 = vertcat(@5, @3, @8, @22, @27, @18) */
  rr=w28;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w08;
  *rr++ = w22;
  *rr++ = w27;
  *rr++ = w18;
  /* #80: @5 = 0.01 */
  w05 = 1.0000000000000000e-02;
  /* #81: @29 = (@5*@28) */
  for (i=0, rr=w29, cs=w28; i<6; ++i) (*rr++)  = (w05*(*cs++));
  /* #82: @29 = (@0+@29) */
  for (i=0, rr=w29, cr=w00, cs=w29; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #83: @3 = @29[3] */
  for (rr=(&w03), cs=w29+3; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #84: @8 = @29[2] */
  for (rr=(&w08), cs=w29+2; cs!=w29+3; cs+=1) *rr++ = *cs;
  /* #85: @22 = cos(@8) */
  w22 = cos( w08 );
  /* #86: @27 = (@3*@22) */
  w27  = (w03*w22);
  /* #87: @18 = @29[4] */
  for (rr=(&w18), cs=w29+4; cs!=w29+5; cs+=1) *rr++ = *cs;
  /* #88: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #89: @2 = (@18*@8) */
  w02  = (w18*w08);
  /* #90: @27 = (@27-@2) */
  w27 -= w02;
  /* #91: @2 = @29[1] */
  for (rr=(&w02), cs=w29+1; cs!=w29+2; cs+=1) *rr++ = *cs;
  /* #92: @2 = (@2*@9) */
  w02 *= w09;
  /* #93: @2 = (@7-@2) */
  w02  = (w07-w02);
  /* #94: @2 = fmax(@2,@10) */
  w02  = casadi_fmax(w02,w10);
  /* #95: @27 = (@27/@2) */
  w27 /= w02;
  /* #96: @8 = (@3*@8) */
  w08  = (w03*w08);
  /* #97: @22 = (@18*@22) */
  w22  = (w18*w22);
  /* #98: @8 = (@8+@22) */
  w08 += w22;
  /* #99: @22 = @29[5] */
  for (rr=(&w22), cs=w29+5; cs!=w29+6; cs+=1) *rr++ = *cs;
  /* #100: @2 = (@9*@27) */
  w02  = (w09*w27);
  /* #101: @2 = (@22-@2) */
  w02  = (w22-w02);
  /* #102: @4 = (@17*@22) */
  w04  = (w17*w22);
  /* #103: @4 = (@18+@4) */
  w04  = (w18+w04);
  /* #104: @30 = fmax(@3,@19) */
  w30  = casadi_fmax(w03,w19);
  /* #105: @4 = atan2(@4,@30) */
  w04  = atan2(w04,w30);
  /* #106: @4 = (@16-@4) */
  w04  = (w16-w04);
  /* #107: @4 = (@15*@4) */
  w04  = (w15*w04);
  /* #108: @4 = atan(@4) */
  w04 = atan( w04 );
  /* #109: @4 = (@14*@4) */
  w04  = (w14*w04);
  /* #110: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #111: @4 = (@13*@4) */
  w04  = (w13*w04);
  /* #112: @31 = (@4*@21) */
  w31  = (w04*w21);
  /* #113: @31 = (@11-@31) */
  w31  = (w11-w31);
  /* #114: @32 = (@23*@18) */
  w32  = (w23*w18);
  /* #115: @32 = (@32*@22) */
  w32 *= w22;
  /* #116: @31 = (@31+@32) */
  w31 += w32;
  /* #117: @31 = (@31/@23) */
  w31 /= w23;
  /* #118: @32 = (@26*@22) */
  w32  = (w26*w22);
  /* #119: @18 = (@18-@32) */
  w18 -= w32;
  /* #120: @18 = atan2(@18,@30) */
  w18  = atan2(w18,w30);
  /* #121: @18 = (@25*@18) */
  w18  = (w25*w18);
  /* #122: @18 = (-@18) */
  w18 = (- w18 );
  /* #123: @18 = atan(@18) */
  w18 = atan( w18 );
  /* #124: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #125: @18 = sin(@18) */
  w18 = sin( w18 );
  /* #126: @18 = (@24*@18) */
  w18  = (w24*w18);
  /* #127: @30 = (@4*@20) */
  w30  = (w04*w20);
  /* #128: @30 = (@18+@30) */
  w30  = (w18+w30);
  /* #129: @3 = (@23*@3) */
  w03  = (w23*w03);
  /* #130: @3 = (@3*@22) */
  w03 *= w22;
  /* #131: @30 = (@30-@3) */
  w30 -= w03;
  /* #132: @30 = (@30/@23) */
  w30 /= w23;
  /* #133: @4 = (@17*@4) */
  w04  = (w17*w04);
  /* #134: @4 = (@4*@20) */
  w04 *= w20;
  /* #135: @18 = (@26*@18) */
  w18  = (w26*w18);
  /* #136: @4 = (@4-@18) */
  w04 -= w18;
  /* #137: @4 = (@4/@6) */
  w04 /= w06;
  /* #138: @29 = vertcat(@27, @8, @2, @31, @30, @4) */
  rr=w29;
  *rr++ = w27;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w04;
  /* #139: @33 = (2.*@29) */
  for (i=0, rr=w33, cs=w29; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #140: @28 = (@28+@33) */
  for (i=0, rr=w28, cs=w33; i<6; ++i) (*rr++) += (*cs++);
  /* #141: @29 = (@5*@29) */
  for (i=0, rr=w29, cs=w29; i<6; ++i) (*rr++)  = (w05*(*cs++));
  /* #142: @29 = (@0+@29) */
  for (i=0, rr=w29, cr=w00, cs=w29; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #143: @5 = @29[3] */
  for (rr=(&w05), cs=w29+3; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #144: @27 = @29[2] */
  for (rr=(&w27), cs=w29+2; cs!=w29+3; cs+=1) *rr++ = *cs;
  /* #145: @8 = cos(@27) */
  w08 = cos( w27 );
  /* #146: @2 = (@5*@8) */
  w02  = (w05*w08);
  /* #147: @31 = @29[4] */
  for (rr=(&w31), cs=w29+4; cs!=w29+5; cs+=1) *rr++ = *cs;
  /* #148: @27 = sin(@27) */
  w27 = sin( w27 );
  /* #149: @30 = (@31*@27) */
  w30  = (w31*w27);
  /* #150: @2 = (@2-@30) */
  w02 -= w30;
  /* #151: @30 = @29[1] */
  for (rr=(&w30), cs=w29+1; cs!=w29+2; cs+=1) *rr++ = *cs;
  /* #152: @30 = (@30*@9) */
  w30 *= w09;
  /* #153: @30 = (@7-@30) */
  w30  = (w07-w30);
  /* #154: @30 = fmax(@30,@10) */
  w30  = casadi_fmax(w30,w10);
  /* #155: @2 = (@2/@30) */
  w02 /= w30;
  /* #156: @27 = (@5*@27) */
  w27  = (w05*w27);
  /* #157: @8 = (@31*@8) */
  w08  = (w31*w08);
  /* #158: @27 = (@27+@8) */
  w27 += w08;
  /* #159: @8 = @29[5] */
  for (rr=(&w08), cs=w29+5; cs!=w29+6; cs+=1) *rr++ = *cs;
  /* #160: @30 = (@9*@2) */
  w30  = (w09*w02);
  /* #161: @30 = (@8-@30) */
  w30  = (w08-w30);
  /* #162: @4 = (@17*@8) */
  w04  = (w17*w08);
  /* #163: @4 = (@31+@4) */
  w04  = (w31+w04);
  /* #164: @18 = fmax(@5,@19) */
  w18  = casadi_fmax(w05,w19);
  /* #165: @4 = atan2(@4,@18) */
  w04  = atan2(w04,w18);
  /* #166: @4 = (@16-@4) */
  w04  = (w16-w04);
  /* #167: @4 = (@15*@4) */
  w04  = (w15*w04);
  /* #168: @4 = atan(@4) */
  w04 = atan( w04 );
  /* #169: @4 = (@14*@4) */
  w04  = (w14*w04);
  /* #170: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #171: @4 = (@13*@4) */
  w04  = (w13*w04);
  /* #172: @3 = (@4*@21) */
  w03  = (w04*w21);
  /* #173: @3 = (@11-@3) */
  w03  = (w11-w03);
  /* #174: @22 = (@23*@31) */
  w22  = (w23*w31);
  /* #175: @22 = (@22*@8) */
  w22 *= w08;
  /* #176: @3 = (@3+@22) */
  w03 += w22;
  /* #177: @3 = (@3/@23) */
  w03 /= w23;
  /* #178: @22 = (@26*@8) */
  w22  = (w26*w08);
  /* #179: @31 = (@31-@22) */
  w31 -= w22;
  /* #180: @31 = atan2(@31,@18) */
  w31  = atan2(w31,w18);
  /* #181: @31 = (@25*@31) */
  w31  = (w25*w31);
  /* #182: @31 = (-@31) */
  w31 = (- w31 );
  /* #183: @31 = atan(@31) */
  w31 = atan( w31 );
  /* #184: @31 = (@14*@31) */
  w31  = (w14*w31);
  /* #185: @31 = sin(@31) */
  w31 = sin( w31 );
  /* #186: @31 = (@24*@31) */
  w31  = (w24*w31);
  /* #187: @18 = (@4*@20) */
  w18  = (w04*w20);
  /* #188: @18 = (@31+@18) */
  w18  = (w31+w18);
  /* #189: @5 = (@23*@5) */
  w05  = (w23*w05);
  /* #190: @5 = (@5*@8) */
  w05 *= w08;
  /* #191: @18 = (@18-@5) */
  w18 -= w05;
  /* #192: @18 = (@18/@23) */
  w18 /= w23;
  /* #193: @4 = (@17*@4) */
  w04  = (w17*w04);
  /* #194: @4 = (@4*@20) */
  w04 *= w20;
  /* #195: @31 = (@26*@31) */
  w31  = (w26*w31);
  /* #196: @4 = (@4-@31) */
  w04 -= w31;
  /* #197: @4 = (@4/@6) */
  w04 /= w06;
  /* #198: @29 = vertcat(@2, @27, @30, @3, @18, @4) */
  rr=w29;
  *rr++ = w02;
  *rr++ = w27;
  *rr++ = w30;
  *rr++ = w03;
  *rr++ = w18;
  *rr++ = w04;
  /* #199: @33 = (2.*@29) */
  for (i=0, rr=w33, cs=w29; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #200: @28 = (@28+@33) */
  for (i=0, rr=w28, cs=w33; i<6; ++i) (*rr++) += (*cs++);
  /* #201: @2 = 0.02 */
  w02 = 2.0000000000000000e-02;
  /* #202: @29 = (@2*@29) */
  for (i=0, rr=w29, cs=w29; i<6; ++i) (*rr++)  = (w02*(*cs++));
  /* #203: @29 = (@0+@29) */
  for (i=0, rr=w29, cr=w00, cs=w29; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #204: @2 = @29[3] */
  for (rr=(&w02), cs=w29+3; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #205: @27 = @29[2] */
  for (rr=(&w27), cs=w29+2; cs!=w29+3; cs+=1) *rr++ = *cs;
  /* #206: @30 = cos(@27) */
  w30 = cos( w27 );
  /* #207: @3 = (@2*@30) */
  w03  = (w02*w30);
  /* #208: @18 = @29[4] */
  for (rr=(&w18), cs=w29+4; cs!=w29+5; cs+=1) *rr++ = *cs;
  /* #209: @27 = sin(@27) */
  w27 = sin( w27 );
  /* #210: @4 = (@18*@27) */
  w04  = (w18*w27);
  /* #211: @3 = (@3-@4) */
  w03 -= w04;
  /* #212: @4 = @29[1] */
  for (rr=(&w04), cs=w29+1; cs!=w29+2; cs+=1) *rr++ = *cs;
  /* #213: @4 = (@4*@9) */
  w04 *= w09;
  /* #214: @7 = (@7-@4) */
  w07 -= w04;
  /* #215: @7 = fmax(@7,@10) */
  w07  = casadi_fmax(w07,w10);
  /* #216: @3 = (@3/@7) */
  w03 /= w07;
  /* #217: @27 = (@2*@27) */
  w27  = (w02*w27);
  /* #218: @30 = (@18*@30) */
  w30  = (w18*w30);
  /* #219: @27 = (@27+@30) */
  w27 += w30;
  /* #220: @30 = @29[5] */
  for (rr=(&w30), cs=w29+5; cs!=w29+6; cs+=1) *rr++ = *cs;
  /* #221: @9 = (@9*@3) */
  w09 *= w03;
  /* #222: @9 = (@30-@9) */
  w09  = (w30-w09);
  /* #223: @7 = (@17*@30) */
  w07  = (w17*w30);
  /* #224: @7 = (@18+@7) */
  w07  = (w18+w07);
  /* #225: @19 = fmax(@2,@19) */
  w19  = casadi_fmax(w02,w19);
  /* #226: @7 = atan2(@7,@19) */
  w07  = atan2(w07,w19);
  /* #227: @16 = (@16-@7) */
  w16 -= w07;
  /* #228: @15 = (@15*@16) */
  w15 *= w16;
  /* #229: @15 = atan(@15) */
  w15 = atan( w15 );
  /* #230: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #231: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #232: @13 = (@13*@15) */
  w13 *= w15;
  /* #233: @21 = (@13*@21) */
  w21  = (w13*w21);
  /* #234: @11 = (@11-@21) */
  w11 -= w21;
  /* #235: @21 = (@23*@18) */
  w21  = (w23*w18);
  /* #236: @21 = (@21*@30) */
  w21 *= w30;
  /* #237: @11 = (@11+@21) */
  w11 += w21;
  /* #238: @11 = (@11/@23) */
  w11 /= w23;
  /* #239: @21 = (@26*@30) */
  w21  = (w26*w30);
  /* #240: @18 = (@18-@21) */
  w18 -= w21;
  /* #241: @18 = atan2(@18,@19) */
  w18  = atan2(w18,w19);
  /* #242: @25 = (@25*@18) */
  w25 *= w18;
  /* #243: @25 = (-@25) */
  w25 = (- w25 );
  /* #244: @25 = atan(@25) */
  w25 = atan( w25 );
  /* #245: @14 = (@14*@25) */
  w14 *= w25;
  /* #246: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #247: @24 = (@24*@14) */
  w24 *= w14;
  /* #248: @14 = (@13*@20) */
  w14  = (w13*w20);
  /* #249: @14 = (@24+@14) */
  w14  = (w24+w14);
  /* #250: @2 = (@23*@2) */
  w02  = (w23*w02);
  /* #251: @2 = (@2*@30) */
  w02 *= w30;
  /* #252: @14 = (@14-@2) */
  w14 -= w02;
  /* #253: @14 = (@14/@23) */
  w14 /= w23;
  /* #254: @17 = (@17*@13) */
  w17 *= w13;
  /* #255: @17 = (@17*@20) */
  w17 *= w20;
  /* #256: @26 = (@26*@24) */
  w26 *= w24;
  /* #257: @17 = (@17-@26) */
  w17 -= w26;
  /* #258: @17 = (@17/@6) */
  w17 /= w06;
  /* #259: @29 = vertcat(@3, @27, @9, @11, @14, @17) */
  rr=w29;
  *rr++ = w03;
  *rr++ = w27;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w17;
  /* #260: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<6; ++i) (*rr++) += (*cs++);
  /* #261: @28 = (@1*@28) */
  for (i=0, rr=w28, cs=w28; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #262: @0 = (@0+@28) */
  for (i=0, rr=w00, cs=w28; i<6; ++i) (*rr++) += (*cs++);
  /* #263: output[0][0] = @0 */
  casadi_copy(w00, 6, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_frenet_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 55;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 55*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
