/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_nmpc_stable_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* f1tenth_nmpc_stable_dyn_disc_phi_fun:(i0[6],i1[2],i2)->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, *w12=w+17, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, *w30=w+36, *w31=w+42, w32, w33, w34;
  casadi_real *w35=w+51;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = 0.00333333 */
  w01 = 3.3333333333333335e-03;
  /* #2: @2 = @0[3] */
  for (rr=(&w02), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #3: @3 = @0[2] */
  for (rr=(&w03), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #4: @4 = cos(@3) */
  w04 = cos( w03 );
  /* #5: @5 = (@2*@4) */
  w05  = (w02*w04);
  /* #6: @6 = @0[4] */
  for (rr=(&w06), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #7: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #8: @7 = (@6*@3) */
  w07  = (w06*w03);
  /* #9: @5 = (@5-@7) */
  w05 -= w07;
  /* #10: @7 = 1 */
  w07 = 1.;
  /* #11: @8 = @0[1] */
  for (rr=(&w08), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #12: @9 = input[2][0] */
  w09 = arg[2] ? arg[2][0] : 0;
  /* #13: @8 = (@8*@9) */
  w08 *= w09;
  /* #14: @8 = (@7-@8) */
  w08  = (w07-w08);
  /* #15: @10 = 0.001 */
  w10 = 1.0000000000000000e-03;
  /* #16: @8 = fmax(@8,@10) */
  w08  = casadi_fmax(w08,w10);
  /* #17: @5 = (@5/@8) */
  w05 /= w08;
  /* #18: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #19: @4 = (@6*@4) */
  w04  = (w06*w04);
  /* #20: @3 = (@3+@4) */
  w03 += w04;
  /* #21: @4 = @0[5] */
  for (rr=(&w04), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #22: @8 = (@9*@5) */
  w08  = (w09*w05);
  /* #23: @8 = (@4-@8) */
  w08  = (w04-w08);
  /* #24: @11 = 20 */
  w11 = 20.;
  /* #25: @12 = input[1][0] */
  casadi_copy(arg[1], 2, w12);
  /* #26: @13 = @12[0] */
  for (rr=(&w13), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #27: @14 = 0 */
  w14 = 0.;
  /* #28: @13 = fmax(@13,@14) */
  w13  = casadi_fmax(w13,w14);
  /* #29: @13 = fmin(@13,@7) */
  w13  = casadi_fmin(w13,w07);
  /* #30: @11 = (@11*@13) */
  w11 *= w13;
  /* #31: @13 = 0.05 */
  w13 = 5.0000000000000003e-02;
  /* #32: @11 = (@11-@13) */
  w11 -= w13;
  /* #33: @13 = 134.585 */
  w13 = 1.3458500000000001e+02;
  /* #34: @15 = 1.2 */
  w15 = 1.2000000000000000e+00;
  /* #35: @16 = 9.242 */
  w16 = 9.2420000000000009e+00;
  /* #36: @17 = @12[1] */
  for (rr=(&w17), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #37: @18 = -0.35 */
  w18 = -3.4999999999999998e-01;
  /* #38: @17 = fmax(@17,@18) */
  w17  = casadi_fmax(w17,w18);
  /* #39: @18 = 0.35 */
  w18 = 3.4999999999999998e-01;
  /* #40: @17 = fmin(@17,@18) */
  w17  = casadi_fmin(w17,w18);
  /* #41: @18 = 0.15875 */
  w18 = 1.5875000000000000e-01;
  /* #42: @19 = (@18*@4) */
  w19  = (w18*w04);
  /* #43: @19 = (@6+@19) */
  w19  = (w06+w19);
  /* #44: @20 = 0.2 */
  w20 = 2.0000000000000001e-01;
  /* #45: @21 = fmax(@2,@20) */
  w21  = casadi_fmax(w02,w20);
  /* #46: @19 = atan2(@19,@21) */
  w19  = atan2(w19,w21);
  /* #47: @19 = (@17-@19) */
  w19  = (w17-w19);
  /* #48: @22 = -1.2 */
  w22 = -1.2000000000000000e+00;
  /* #49: @19 = fmax(@19,@22) */
  w19  = casadi_fmax(w19,w22);
  /* #50: @19 = fmin(@19,@15) */
  w19  = casadi_fmin(w19,w15);
  /* #51: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #52: @19 = atan(@19) */
  w19 = atan( w19 );
  /* #53: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #54: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #55: @19 = (@13*@19) */
  w19  = (w13*w19);
  /* #56: @23 = sin(@17) */
  w23 = sin( w17 );
  /* #57: @24 = (@19*@23) */
  w24  = (w19*w23);
  /* #58: @24 = (@11-@24) */
  w24  = (w11-w24);
  /* #59: @25 = 3.47 */
  w25 = 3.4700000000000002e+00;
  /* #60: @26 = (@25*@6) */
  w26  = (w25*w06);
  /* #61: @26 = (@26*@4) */
  w26 *= w04;
  /* #62: @24 = (@24+@26) */
  w24 += w26;
  /* #63: @24 = (@24/@25) */
  w24 /= w25;
  /* #64: @26 = 159.919 */
  w26 = 1.5991900000000001e+02;
  /* #65: @27 = 17.716 */
  w27 = 1.7716000000000001e+01;
  /* #66: @28 = 0.17145 */
  w28 = 1.7144999999999999e-01;
  /* #67: @29 = (@28*@4) */
  w29  = (w28*w04);
  /* #68: @6 = (@6-@29) */
  w06 -= w29;
  /* #69: @6 = atan2(@6,@21) */
  w06  = atan2(w06,w21);
  /* #70: @6 = (-@6) */
  w06 = (- w06 );
  /* #71: @6 = fmax(@6,@22) */
  w06  = casadi_fmax(w06,w22);
  /* #72: @6 = fmin(@6,@15) */
  w06  = casadi_fmin(w06,w15);
  /* #73: @6 = (@27*@6) */
  w06  = (w27*w06);
  /* #74: @6 = atan(@6) */
  w06 = atan( w06 );
  /* #75: @6 = (@15*@6) */
  w06  = (w15*w06);
  /* #76: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #77: @6 = (@26*@6) */
  w06  = (w26*w06);
  /* #78: @21 = cos(@17) */
  w21 = cos( w17 );
  /* #79: @29 = (@19*@21) */
  w29  = (w19*w21);
  /* #80: @29 = (@6+@29) */
  w29  = (w06+w29);
  /* #81: @2 = (@25*@2) */
  w02  = (w25*w02);
  /* #82: @2 = (@2*@4) */
  w02 *= w04;
  /* #83: @29 = (@29-@2) */
  w29 -= w02;
  /* #84: @29 = (@29/@25) */
  w29 /= w25;
  /* #85: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #86: @19 = (@19*@21) */
  w19 *= w21;
  /* #87: @6 = (@28*@6) */
  w06  = (w28*w06);
  /* #88: @19 = (@19-@6) */
  w19 -= w06;
  /* #89: @6 = 0.04712 */
  w06 = 4.7120000000000002e-02;
  /* #90: @19 = (@19/@6) */
  w19 /= w06;
  /* #91: @30 = vertcat(@5, @3, @8, @24, @29, @19) */
  rr=w30;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w08;
  *rr++ = w24;
  *rr++ = w29;
  *rr++ = w19;
  /* #92: @5 = 0.01 */
  w05 = 1.0000000000000000e-02;
  /* #93: @31 = (@5*@30) */
  for (i=0, rr=w31, cs=w30; i<6; ++i) (*rr++)  = (w05*(*cs++));
  /* #94: @31 = (@0+@31) */
  for (i=0, rr=w31, cr=w00, cs=w31; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #95: @3 = @31[3] */
  for (rr=(&w03), cs=w31+3; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #96: @8 = @31[2] */
  for (rr=(&w08), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #97: @24 = cos(@8) */
  w24 = cos( w08 );
  /* #98: @29 = (@3*@24) */
  w29  = (w03*w24);
  /* #99: @19 = @31[4] */
  for (rr=(&w19), cs=w31+4; cs!=w31+5; cs+=1) *rr++ = *cs;
  /* #100: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #101: @2 = (@19*@8) */
  w02  = (w19*w08);
  /* #102: @29 = (@29-@2) */
  w29 -= w02;
  /* #103: @2 = @31[1] */
  for (rr=(&w02), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #104: @2 = (@2*@9) */
  w02 *= w09;
  /* #105: @2 = (@7-@2) */
  w02  = (w07-w02);
  /* #106: @2 = fmax(@2,@10) */
  w02  = casadi_fmax(w02,w10);
  /* #107: @29 = (@29/@2) */
  w29 /= w02;
  /* #108: @8 = (@3*@8) */
  w08  = (w03*w08);
  /* #109: @24 = (@19*@24) */
  w24  = (w19*w24);
  /* #110: @8 = (@8+@24) */
  w08 += w24;
  /* #111: @24 = @31[5] */
  for (rr=(&w24), cs=w31+5; cs!=w31+6; cs+=1) *rr++ = *cs;
  /* #112: @2 = (@9*@29) */
  w02  = (w09*w29);
  /* #113: @2 = (@24-@2) */
  w02  = (w24-w02);
  /* #114: @4 = (@18*@24) */
  w04  = (w18*w24);
  /* #115: @4 = (@19+@4) */
  w04  = (w19+w04);
  /* #116: @32 = fmax(@3,@20) */
  w32  = casadi_fmax(w03,w20);
  /* #117: @4 = atan2(@4,@32) */
  w04  = atan2(w04,w32);
  /* #118: @4 = (@17-@4) */
  w04  = (w17-w04);
  /* #119: @4 = fmax(@4,@22) */
  w04  = casadi_fmax(w04,w22);
  /* #120: @4 = fmin(@4,@15) */
  w04  = casadi_fmin(w04,w15);
  /* #121: @4 = (@16*@4) */
  w04  = (w16*w04);
  /* #122: @4 = atan(@4) */
  w04 = atan( w04 );
  /* #123: @4 = (@15*@4) */
  w04  = (w15*w04);
  /* #124: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #125: @4 = (@13*@4) */
  w04  = (w13*w04);
  /* #126: @33 = (@4*@23) */
  w33  = (w04*w23);
  /* #127: @33 = (@11-@33) */
  w33  = (w11-w33);
  /* #128: @34 = (@25*@19) */
  w34  = (w25*w19);
  /* #129: @34 = (@34*@24) */
  w34 *= w24;
  /* #130: @33 = (@33+@34) */
  w33 += w34;
  /* #131: @33 = (@33/@25) */
  w33 /= w25;
  /* #132: @34 = (@28*@24) */
  w34  = (w28*w24);
  /* #133: @19 = (@19-@34) */
  w19 -= w34;
  /* #134: @19 = atan2(@19,@32) */
  w19  = atan2(w19,w32);
  /* #135: @19 = (-@19) */
  w19 = (- w19 );
  /* #136: @19 = fmax(@19,@22) */
  w19  = casadi_fmax(w19,w22);
  /* #137: @19 = fmin(@19,@15) */
  w19  = casadi_fmin(w19,w15);
  /* #138: @19 = (@27*@19) */
  w19  = (w27*w19);
  /* #139: @19 = atan(@19) */
  w19 = atan( w19 );
  /* #140: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #141: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #142: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #143: @32 = (@4*@21) */
  w32  = (w04*w21);
  /* #144: @32 = (@19+@32) */
  w32  = (w19+w32);
  /* #145: @3 = (@25*@3) */
  w03  = (w25*w03);
  /* #146: @3 = (@3*@24) */
  w03 *= w24;
  /* #147: @32 = (@32-@3) */
  w32 -= w03;
  /* #148: @32 = (@32/@25) */
  w32 /= w25;
  /* #149: @4 = (@18*@4) */
  w04  = (w18*w04);
  /* #150: @4 = (@4*@21) */
  w04 *= w21;
  /* #151: @19 = (@28*@19) */
  w19  = (w28*w19);
  /* #152: @4 = (@4-@19) */
  w04 -= w19;
  /* #153: @4 = (@4/@6) */
  w04 /= w06;
  /* #154: @31 = vertcat(@29, @8, @2, @33, @32, @4) */
  rr=w31;
  *rr++ = w29;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w33;
  *rr++ = w32;
  *rr++ = w04;
  /* #155: @35 = (2.*@31) */
  for (i=0, rr=w35, cs=w31; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #156: @30 = (@30+@35) */
  for (i=0, rr=w30, cs=w35; i<6; ++i) (*rr++) += (*cs++);
  /* #157: @31 = (@5*@31) */
  for (i=0, rr=w31, cs=w31; i<6; ++i) (*rr++)  = (w05*(*cs++));
  /* #158: @31 = (@0+@31) */
  for (i=0, rr=w31, cr=w00, cs=w31; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #159: @5 = @31[3] */
  for (rr=(&w05), cs=w31+3; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #160: @29 = @31[2] */
  for (rr=(&w29), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #161: @8 = cos(@29) */
  w08 = cos( w29 );
  /* #162: @2 = (@5*@8) */
  w02  = (w05*w08);
  /* #163: @33 = @31[4] */
  for (rr=(&w33), cs=w31+4; cs!=w31+5; cs+=1) *rr++ = *cs;
  /* #164: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #165: @32 = (@33*@29) */
  w32  = (w33*w29);
  /* #166: @2 = (@2-@32) */
  w02 -= w32;
  /* #167: @32 = @31[1] */
  for (rr=(&w32), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #168: @32 = (@32*@9) */
  w32 *= w09;
  /* #169: @32 = (@7-@32) */
  w32  = (w07-w32);
  /* #170: @32 = fmax(@32,@10) */
  w32  = casadi_fmax(w32,w10);
  /* #171: @2 = (@2/@32) */
  w02 /= w32;
  /* #172: @29 = (@5*@29) */
  w29  = (w05*w29);
  /* #173: @8 = (@33*@8) */
  w08  = (w33*w08);
  /* #174: @29 = (@29+@8) */
  w29 += w08;
  /* #175: @8 = @31[5] */
  for (rr=(&w08), cs=w31+5; cs!=w31+6; cs+=1) *rr++ = *cs;
  /* #176: @32 = (@9*@2) */
  w32  = (w09*w02);
  /* #177: @32 = (@8-@32) */
  w32  = (w08-w32);
  /* #178: @4 = (@18*@8) */
  w04  = (w18*w08);
  /* #179: @4 = (@33+@4) */
  w04  = (w33+w04);
  /* #180: @19 = fmax(@5,@20) */
  w19  = casadi_fmax(w05,w20);
  /* #181: @4 = atan2(@4,@19) */
  w04  = atan2(w04,w19);
  /* #182: @4 = (@17-@4) */
  w04  = (w17-w04);
  /* #183: @4 = fmax(@4,@22) */
  w04  = casadi_fmax(w04,w22);
  /* #184: @4 = fmin(@4,@15) */
  w04  = casadi_fmin(w04,w15);
  /* #185: @4 = (@16*@4) */
  w04  = (w16*w04);
  /* #186: @4 = atan(@4) */
  w04 = atan( w04 );
  /* #187: @4 = (@15*@4) */
  w04  = (w15*w04);
  /* #188: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #189: @4 = (@13*@4) */
  w04  = (w13*w04);
  /* #190: @3 = (@4*@23) */
  w03  = (w04*w23);
  /* #191: @3 = (@11-@3) */
  w03  = (w11-w03);
  /* #192: @24 = (@25*@33) */
  w24  = (w25*w33);
  /* #193: @24 = (@24*@8) */
  w24 *= w08;
  /* #194: @3 = (@3+@24) */
  w03 += w24;
  /* #195: @3 = (@3/@25) */
  w03 /= w25;
  /* #196: @24 = (@28*@8) */
  w24  = (w28*w08);
  /* #197: @33 = (@33-@24) */
  w33 -= w24;
  /* #198: @33 = atan2(@33,@19) */
  w33  = atan2(w33,w19);
  /* #199: @33 = (-@33) */
  w33 = (- w33 );
  /* #200: @33 = fmax(@33,@22) */
  w33  = casadi_fmax(w33,w22);
  /* #201: @33 = fmin(@33,@15) */
  w33  = casadi_fmin(w33,w15);
  /* #202: @33 = (@27*@33) */
  w33  = (w27*w33);
  /* #203: @33 = atan(@33) */
  w33 = atan( w33 );
  /* #204: @33 = (@15*@33) */
  w33  = (w15*w33);
  /* #205: @33 = sin(@33) */
  w33 = sin( w33 );
  /* #206: @33 = (@26*@33) */
  w33  = (w26*w33);
  /* #207: @19 = (@4*@21) */
  w19  = (w04*w21);
  /* #208: @19 = (@33+@19) */
  w19  = (w33+w19);
  /* #209: @5 = (@25*@5) */
  w05  = (w25*w05);
  /* #210: @5 = (@5*@8) */
  w05 *= w08;
  /* #211: @19 = (@19-@5) */
  w19 -= w05;
  /* #212: @19 = (@19/@25) */
  w19 /= w25;
  /* #213: @4 = (@18*@4) */
  w04  = (w18*w04);
  /* #214: @4 = (@4*@21) */
  w04 *= w21;
  /* #215: @33 = (@28*@33) */
  w33  = (w28*w33);
  /* #216: @4 = (@4-@33) */
  w04 -= w33;
  /* #217: @4 = (@4/@6) */
  w04 /= w06;
  /* #218: @31 = vertcat(@2, @29, @32, @3, @19, @4) */
  rr=w31;
  *rr++ = w02;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w03;
  *rr++ = w19;
  *rr++ = w04;
  /* #219: @35 = (2.*@31) */
  for (i=0, rr=w35, cs=w31; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #220: @30 = (@30+@35) */
  for (i=0, rr=w30, cs=w35; i<6; ++i) (*rr++) += (*cs++);
  /* #221: @2 = 0.02 */
  w02 = 2.0000000000000000e-02;
  /* #222: @31 = (@2*@31) */
  for (i=0, rr=w31, cs=w31; i<6; ++i) (*rr++)  = (w02*(*cs++));
  /* #223: @31 = (@0+@31) */
  for (i=0, rr=w31, cr=w00, cs=w31; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #224: @2 = @31[3] */
  for (rr=(&w02), cs=w31+3; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #225: @29 = @31[2] */
  for (rr=(&w29), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #226: @32 = cos(@29) */
  w32 = cos( w29 );
  /* #227: @3 = (@2*@32) */
  w03  = (w02*w32);
  /* #228: @19 = @31[4] */
  for (rr=(&w19), cs=w31+4; cs!=w31+5; cs+=1) *rr++ = *cs;
  /* #229: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #230: @4 = (@19*@29) */
  w04  = (w19*w29);
  /* #231: @3 = (@3-@4) */
  w03 -= w04;
  /* #232: @4 = @31[1] */
  for (rr=(&w04), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #233: @4 = (@4*@9) */
  w04 *= w09;
  /* #234: @7 = (@7-@4) */
  w07 -= w04;
  /* #235: @7 = fmax(@7,@10) */
  w07  = casadi_fmax(w07,w10);
  /* #236: @3 = (@3/@7) */
  w03 /= w07;
  /* #237: @29 = (@2*@29) */
  w29  = (w02*w29);
  /* #238: @32 = (@19*@32) */
  w32  = (w19*w32);
  /* #239: @29 = (@29+@32) */
  w29 += w32;
  /* #240: @32 = @31[5] */
  for (rr=(&w32), cs=w31+5; cs!=w31+6; cs+=1) *rr++ = *cs;
  /* #241: @9 = (@9*@3) */
  w09 *= w03;
  /* #242: @9 = (@32-@9) */
  w09  = (w32-w09);
  /* #243: @7 = (@18*@32) */
  w07  = (w18*w32);
  /* #244: @7 = (@19+@7) */
  w07  = (w19+w07);
  /* #245: @20 = fmax(@2,@20) */
  w20  = casadi_fmax(w02,w20);
  /* #246: @7 = atan2(@7,@20) */
  w07  = atan2(w07,w20);
  /* #247: @17 = (@17-@7) */
  w17 -= w07;
  /* #248: @17 = fmax(@17,@22) */
  w17  = casadi_fmax(w17,w22);
  /* #249: @17 = fmin(@17,@15) */
  w17  = casadi_fmin(w17,w15);
  /* #250: @16 = (@16*@17) */
  w16 *= w17;
  /* #251: @16 = atan(@16) */
  w16 = atan( w16 );
  /* #252: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #253: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #254: @13 = (@13*@16) */
  w13 *= w16;
  /* #255: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #256: @11 = (@11-@23) */
  w11 -= w23;
  /* #257: @23 = (@25*@19) */
  w23  = (w25*w19);
  /* #258: @23 = (@23*@32) */
  w23 *= w32;
  /* #259: @11 = (@11+@23) */
  w11 += w23;
  /* #260: @11 = (@11/@25) */
  w11 /= w25;
  /* #261: @23 = (@28*@32) */
  w23  = (w28*w32);
  /* #262: @19 = (@19-@23) */
  w19 -= w23;
  /* #263: @19 = atan2(@19,@20) */
  w19  = atan2(w19,w20);
  /* #264: @19 = (-@19) */
  w19 = (- w19 );
  /* #265: @19 = fmax(@19,@22) */
  w19  = casadi_fmax(w19,w22);
  /* #266: @19 = fmin(@19,@15) */
  w19  = casadi_fmin(w19,w15);
  /* #267: @27 = (@27*@19) */
  w27 *= w19;
  /* #268: @27 = atan(@27) */
  w27 = atan( w27 );
  /* #269: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #270: @27 = sin(@27) */
  w27 = sin( w27 );
  /* #271: @26 = (@26*@27) */
  w26 *= w27;
  /* #272: @27 = (@13*@21) */
  w27  = (w13*w21);
  /* #273: @27 = (@26+@27) */
  w27  = (w26+w27);
  /* #274: @2 = (@25*@2) */
  w02  = (w25*w02);
  /* #275: @2 = (@2*@32) */
  w02 *= w32;
  /* #276: @27 = (@27-@2) */
  w27 -= w02;
  /* #277: @27 = (@27/@25) */
  w27 /= w25;
  /* #278: @18 = (@18*@13) */
  w18 *= w13;
  /* #279: @18 = (@18*@21) */
  w18 *= w21;
  /* #280: @28 = (@28*@26) */
  w28 *= w26;
  /* #281: @18 = (@18-@28) */
  w18 -= w28;
  /* #282: @18 = (@18/@6) */
  w18 /= w06;
  /* #283: @31 = vertcat(@3, @29, @9, @11, @27, @18) */
  rr=w31;
  *rr++ = w03;
  *rr++ = w29;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w27;
  *rr++ = w18;
  /* #284: @30 = (@30+@31) */
  for (i=0, rr=w30, cs=w31; i<6; ++i) (*rr++) += (*cs++);
  /* #285: @30 = (@1*@30) */
  for (i=0, rr=w30, cs=w30; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #286: @0 = (@0+@30) */
  for (i=0, rr=w00, cs=w30; i<6; ++i) (*rr++) += (*cs++);
  /* #287: @1 = @0[3] */
  for (rr=(&w01), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #288: @1 = fmax(@1,@14) */
  w01  = casadi_fmax(w01,w14);
  /* #289: @14 = 8 */
  w14 = 8.;
  /* #290: @1 = fmin(@1,@14) */
  w01  = casadi_fmin(w01,w14);
  /* #291: (@0[3] = @1) */
  for (rr=w00+3, cs=(&w01); rr!=w00+4; rr+=1) *rr = *cs++;
  /* #292: @1 = @0[1] */
  for (rr=(&w01), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #293: @14 = -0.2625 */
  w14 = -2.6249999999999996e-01;
  /* #294: @1 = fmax(@1,@14) */
  w01  = casadi_fmax(w01,w14);
  /* #295: @14 = 0.2625 */
  w14 = 2.6249999999999996e-01;
  /* #296: @1 = fmin(@1,@14) */
  w01  = casadi_fmin(w01,w14);
  /* #297: (@0[1] = @1) */
  for (rr=w00+1, cs=(&w01); rr!=w00+2; rr+=1) *rr = *cs++;
  /* #298: @1 = @0[2] */
  for (rr=(&w01), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #299: @1 = fmax(@1,@22) */
  w01  = casadi_fmax(w01,w22);
  /* #300: @1 = fmin(@1,@15) */
  w01  = casadi_fmin(w01,w15);
  /* #301: (@0[2] = @1) */
  for (rr=w00+2, cs=(&w01); rr!=w00+3; rr+=1) *rr = *cs++;
  /* #302: @1 = @0[4] */
  for (rr=(&w01), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #303: @15 = -4 */
  w15 = -4.;
  /* #304: @1 = fmax(@1,@15) */
  w01  = casadi_fmax(w01,w15);
  /* #305: @15 = 4 */
  w15 = 4.;
  /* #306: @1 = fmin(@1,@15) */
  w01  = casadi_fmin(w01,w15);
  /* #307: (@0[4] = @1) */
  for (rr=w00+4, cs=(&w01); rr!=w00+5; rr+=1) *rr = *cs++;
  /* #308: @1 = @0[5] */
  for (rr=(&w01), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #309: @15 = -12 */
  w15 = -12.;
  /* #310: @1 = fmax(@1,@15) */
  w01  = casadi_fmax(w01,w15);
  /* #311: @15 = 12 */
  w15 = 12.;
  /* #312: @1 = fmin(@1,@15) */
  w01  = casadi_fmin(w01,w15);
  /* #313: (@0[5] = @1) */
  for (rr=w00+5, cs=(&w01); rr!=w00+6; rr+=1) *rr = *cs++;
  /* #314: output[0][0] = @0 */
  casadi_copy(w00, 6, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_nmpc_stable_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_nmpc_stable_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_nmpc_stable_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_nmpc_stable_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_nmpc_stable_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_nmpc_stable_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_nmpc_stable_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_nmpc_stable_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_nmpc_stable_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_nmpc_stable_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_nmpc_stable_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_nmpc_stable_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_nmpc_stable_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_nmpc_stable_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_nmpc_stable_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_nmpc_stable_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 57;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_nmpc_stable_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 57*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
