/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_mpcc_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenth_mpcc_dyn_disc_phi_fun:(i0[9],i1[2],i2)->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, *w12=w+20, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, *w30=w+39, *w31=w+48, w32, w33, w34;
  casadi_real *w35=w+60;
  const casadi_real *cr, *cs, *wr00;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = 0.00333333 */
  w01 = 3.3333333333333335e-03;
  /* #2: @2 = @0[3] */
  w02 = wr00[3];
  /* #3: @3 = @0[2] */
  w03 = wr00[2];
  /* #4: @4 = cos(@3) */
  w04 = cos( w03 );
  /* #5: @5 = (@2*@4) */
  w05  = (w02*w04);
  /* #6: @6 = @0[4] */
  w06 = wr00[4];
  /* #7: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #8: @7 = (@6*@3) */
  w07  = (w06*w03);
  /* #9: @5 = (@5-@7) */
  w05 -= w07;
  /* #10: @7 = 1 */
  w07 = 1.;
  /* #11: @8 = @0[1] */
  w08 = wr00[1];
  /* #12: @9 = input[2][0] */
  w09 = arg[2] ? arg[2][0] : 0;
  /* #13: @8 = (@8*@9) */
  w08 *= w09;
  /* #14: @8 = (@7-@8) */
  w08  = (w07-w08);
  /* #15: @10 = sign(@8) */
  w10 = casadi_sign( w08 );
  /* #16: @8 = fabs(@8) */
  w08 = casadi_fabs( w08 );
  /* #17: @11 = 1e-06 */
  w11 = 9.9999999999999995e-07;
  /* #18: @8 = fmax(@8,@11) */
  w08  = casadi_fmax(w08,w11);
  /* #19: @10 = (@10*@8) */
  w10 *= w08;
  /* #20: @5 = (@5/@10) */
  w05 /= w10;
  /* #21: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #22: @4 = (@6*@4) */
  w04  = (w06*w04);
  /* #23: @3 = (@3+@4) */
  w03 += w04;
  /* #24: @4 = @0[5] */
  w04 = wr00[5];
  /* #25: @10 = (@9*@5) */
  w10  = (w09*w05);
  /* #26: @10 = (@4-@10) */
  w10  = (w04-w10);
  /* #27: @8 = 20 */
  w08 = 20.;
  /* #28: @12 = input[1][0] */
  casadi_copy(arg[1], 2, w12);
  /* #29: @13 = @12[0] */
  for (rr=(&w13), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #30: @14 = 0 */
  w14 = 0.;
  /* #31: @13 = fmax(@13,@14) */
  w13  = casadi_fmax(w13,w14);
  /* #32: @13 = fmin(@13,@7) */
  w13  = casadi_fmin(w13,w07);
  /* #33: @8 = (@8*@13) */
  w08 *= w13;
  /* #34: @14 = 0.05 */
  w14 = 5.0000000000000003e-02;
  /* #35: @8 = (@8-@14) */
  w08 -= w14;
  /* #36: @14 = 134.585 */
  w14 = 1.3458500000000001e+02;
  /* #37: @15 = 1.2 */
  w15 = 1.2000000000000000e+00;
  /* #38: @16 = 9.242 */
  w16 = 9.2420000000000009e+00;
  /* #39: @17 = @12[1] */
  for (rr=(&w17), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #40: @18 = -0.35 */
  w18 = -3.4999999999999998e-01;
  /* #41: @17 = fmax(@17,@18) */
  w17  = casadi_fmax(w17,w18);
  /* #42: @18 = 0.35 */
  w18 = 3.4999999999999998e-01;
  /* #43: @17 = fmin(@17,@18) */
  w17  = casadi_fmin(w17,w18);
  /* #44: @18 = 0.15875 */
  w18 = 1.5875000000000000e-01;
  /* #45: @19 = (@18*@4) */
  w19  = (w18*w04);
  /* #46: @19 = (@6+@19) */
  w19  = (w06+w19);
  /* #47: @20 = 0.001 */
  w20 = 1.0000000000000000e-03;
  /* #48: @21 = fmax(@2,@20) */
  w21  = casadi_fmax(w02,w20);
  /* #49: @19 = atan2(@19,@21) */
  w19  = atan2(w19,w21);
  /* #50: @19 = (@17-@19) */
  w19  = (w17-w19);
  /* #51: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #52: @19 = atan(@19) */
  w19 = atan( w19 );
  /* #53: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #54: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #55: @19 = (@14*@19) */
  w19  = (w14*w19);
  /* #56: @22 = sin(@17) */
  w22 = sin( w17 );
  /* #57: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #58: @23 = (@8-@23) */
  w23  = (w08-w23);
  /* #59: @24 = 3.47 */
  w24 = 3.4700000000000002e+00;
  /* #60: @25 = (@24*@6) */
  w25  = (w24*w06);
  /* #61: @25 = (@25*@4) */
  w25 *= w04;
  /* #62: @23 = (@23+@25) */
  w23 += w25;
  /* #63: @23 = (@23/@24) */
  w23 /= w24;
  /* #64: @25 = 159.919 */
  w25 = 1.5991900000000001e+02;
  /* #65: @26 = 17.716 */
  w26 = 1.7716000000000001e+01;
  /* #66: @27 = 0.17145 */
  w27 = 1.7144999999999999e-01;
  /* #67: @28 = (@27*@4) */
  w28  = (w27*w04);
  /* #68: @6 = (@6-@28) */
  w06 -= w28;
  /* #69: @6 = atan2(@6,@21) */
  w06  = atan2(w06,w21);
  /* #70: @6 = (@26*@6) */
  w06  = (w26*w06);
  /* #71: @6 = (-@6) */
  w06 = (- w06 );
  /* #72: @6 = atan(@6) */
  w06 = atan( w06 );
  /* #73: @6 = (@15*@6) */
  w06  = (w15*w06);
  /* #74: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #75: @6 = (@25*@6) */
  w06  = (w25*w06);
  /* #76: @21 = cos(@17) */
  w21 = cos( w17 );
  /* #77: @28 = (@19*@21) */
  w28  = (w19*w21);
  /* #78: @28 = (@6+@28) */
  w28  = (w06+w28);
  /* #79: @2 = (@24*@2) */
  w02  = (w24*w02);
  /* #80: @2 = (@2*@4) */
  w02 *= w04;
  /* #81: @28 = (@28-@2) */
  w28 -= w02;
  /* #82: @28 = (@28/@24) */
  w28 /= w24;
  /* #83: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #84: @19 = (@19*@21) */
  w19 *= w21;
  /* #85: @6 = (@27*@6) */
  w06  = (w27*w06);
  /* #86: @19 = (@19-@6) */
  w19 -= w06;
  /* #87: @6 = 0.04712 */
  w06 = 4.7120000000000002e-02;
  /* #88: @19 = (@19/@6) */
  w19 /= w06;
  /* #89: @2 = @0[7] */
  w02 = wr00[7];
  /* #90: @2 = (@13-@2) */
  w02  = (w13-w02);
  /* #91: @4 = 0.02 */
  w04 = 2.0000000000000000e-02;
  /* #92: @2 = (@2/@4) */
  w02 /= w04;
  /* #93: @29 = @0[8] */
  w29 = wr00[8];
  /* #94: @29 = (@17-@29) */
  w29  = (w17-w29);
  /* #95: @29 = (@29/@4) */
  w29 /= w04;
  /* #96: @30 = vertcat(@5, @3, @10, @23, @28, @19, @5, @2, @29) */
  rr=w30;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w10;
  *rr++ = w23;
  *rr++ = w28;
  *rr++ = w19;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w29;
  /* #97: @5 = 0.01 */
  w05 = 1.0000000000000000e-02;
  /* #98: @31 = (@5*@30) */
  for (i=0, rr=w31, cs=w30; i<9; ++i) (*rr++)  = (w05*(*cs++));
  /* #99: @31 = (@0+@31) */
  for (i=0, rr=w31, cr=wr00, cs=w31; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #100: @3 = @31[3] */
  for (rr=(&w03), cs=w31+3; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #101: @10 = @31[2] */
  for (rr=(&w10), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #102: @23 = cos(@10) */
  w23 = cos( w10 );
  /* #103: @28 = (@3*@23) */
  w28  = (w03*w23);
  /* #104: @19 = @31[4] */
  for (rr=(&w19), cs=w31+4; cs!=w31+5; cs+=1) *rr++ = *cs;
  /* #105: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #106: @2 = (@19*@10) */
  w02  = (w19*w10);
  /* #107: @28 = (@28-@2) */
  w28 -= w02;
  /* #108: @2 = @31[1] */
  for (rr=(&w02), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #109: @2 = (@2*@9) */
  w02 *= w09;
  /* #110: @2 = (@7-@2) */
  w02  = (w07-w02);
  /* #111: @29 = sign(@2) */
  w29 = casadi_sign( w02 );
  /* #112: @2 = fabs(@2) */
  w02 = casadi_fabs( w02 );
  /* #113: @2 = fmax(@2,@11) */
  w02  = casadi_fmax(w02,w11);
  /* #114: @29 = (@29*@2) */
  w29 *= w02;
  /* #115: @28 = (@28/@29) */
  w28 /= w29;
  /* #116: @10 = (@3*@10) */
  w10  = (w03*w10);
  /* #117: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #118: @10 = (@10+@23) */
  w10 += w23;
  /* #119: @23 = @31[5] */
  for (rr=(&w23), cs=w31+5; cs!=w31+6; cs+=1) *rr++ = *cs;
  /* #120: @29 = (@9*@28) */
  w29  = (w09*w28);
  /* #121: @29 = (@23-@29) */
  w29  = (w23-w29);
  /* #122: @2 = (@18*@23) */
  w02  = (w18*w23);
  /* #123: @2 = (@19+@2) */
  w02  = (w19+w02);
  /* #124: @32 = fmax(@3,@20) */
  w32  = casadi_fmax(w03,w20);
  /* #125: @2 = atan2(@2,@32) */
  w02  = atan2(w02,w32);
  /* #126: @2 = (@17-@2) */
  w02  = (w17-w02);
  /* #127: @2 = (@16*@2) */
  w02  = (w16*w02);
  /* #128: @2 = atan(@2) */
  w02 = atan( w02 );
  /* #129: @2 = (@15*@2) */
  w02  = (w15*w02);
  /* #130: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #131: @2 = (@14*@2) */
  w02  = (w14*w02);
  /* #132: @33 = (@2*@22) */
  w33  = (w02*w22);
  /* #133: @33 = (@8-@33) */
  w33  = (w08-w33);
  /* #134: @34 = (@24*@19) */
  w34  = (w24*w19);
  /* #135: @34 = (@34*@23) */
  w34 *= w23;
  /* #136: @33 = (@33+@34) */
  w33 += w34;
  /* #137: @33 = (@33/@24) */
  w33 /= w24;
  /* #138: @34 = (@27*@23) */
  w34  = (w27*w23);
  /* #139: @19 = (@19-@34) */
  w19 -= w34;
  /* #140: @19 = atan2(@19,@32) */
  w19  = atan2(w19,w32);
  /* #141: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #142: @19 = (-@19) */
  w19 = (- w19 );
  /* #143: @19 = atan(@19) */
  w19 = atan( w19 );
  /* #144: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #145: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #146: @19 = (@25*@19) */
  w19  = (w25*w19);
  /* #147: @32 = (@2*@21) */
  w32  = (w02*w21);
  /* #148: @32 = (@19+@32) */
  w32  = (w19+w32);
  /* #149: @3 = (@24*@3) */
  w03  = (w24*w03);
  /* #150: @3 = (@3*@23) */
  w03 *= w23;
  /* #151: @32 = (@32-@3) */
  w32 -= w03;
  /* #152: @32 = (@32/@24) */
  w32 /= w24;
  /* #153: @2 = (@18*@2) */
  w02  = (w18*w02);
  /* #154: @2 = (@2*@21) */
  w02 *= w21;
  /* #155: @19 = (@27*@19) */
  w19  = (w27*w19);
  /* #156: @2 = (@2-@19) */
  w02 -= w19;
  /* #157: @2 = (@2/@6) */
  w02 /= w06;
  /* #158: @19 = @31[7] */
  for (rr=(&w19), cs=w31+7; cs!=w31+8; cs+=1) *rr++ = *cs;
  /* #159: @19 = (@13-@19) */
  w19  = (w13-w19);
  /* #160: @19 = (@19/@4) */
  w19 /= w04;
  /* #161: @3 = @31[8] */
  for (rr=(&w03), cs=w31+8; cs!=w31+9; cs+=1) *rr++ = *cs;
  /* #162: @3 = (@17-@3) */
  w03  = (w17-w03);
  /* #163: @3 = (@3/@4) */
  w03 /= w04;
  /* #164: @31 = vertcat(@28, @10, @29, @33, @32, @2, @28, @19, @3) */
  rr=w31;
  *rr++ = w28;
  *rr++ = w10;
  *rr++ = w29;
  *rr++ = w33;
  *rr++ = w32;
  *rr++ = w02;
  *rr++ = w28;
  *rr++ = w19;
  *rr++ = w03;
  /* #165: @35 = (2.*@31) */
  for (i=0, rr=w35, cs=w31; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #166: @30 = (@30+@35) */
  for (i=0, rr=w30, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #167: @31 = (@5*@31) */
  for (i=0, rr=w31, cs=w31; i<9; ++i) (*rr++)  = (w05*(*cs++));
  /* #168: @31 = (@0+@31) */
  for (i=0, rr=w31, cr=wr00, cs=w31; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #169: @5 = @31[3] */
  for (rr=(&w05), cs=w31+3; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #170: @28 = @31[2] */
  for (rr=(&w28), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #171: @10 = cos(@28) */
  w10 = cos( w28 );
  /* #172: @29 = (@5*@10) */
  w29  = (w05*w10);
  /* #173: @33 = @31[4] */
  for (rr=(&w33), cs=w31+4; cs!=w31+5; cs+=1) *rr++ = *cs;
  /* #174: @28 = sin(@28) */
  w28 = sin( w28 );
  /* #175: @32 = (@33*@28) */
  w32  = (w33*w28);
  /* #176: @29 = (@29-@32) */
  w29 -= w32;
  /* #177: @32 = @31[1] */
  for (rr=(&w32), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #178: @32 = (@32*@9) */
  w32 *= w09;
  /* #179: @32 = (@7-@32) */
  w32  = (w07-w32);
  /* #180: @2 = sign(@32) */
  w02 = casadi_sign( w32 );
  /* #181: @32 = fabs(@32) */
  w32 = casadi_fabs( w32 );
  /* #182: @32 = fmax(@32,@11) */
  w32  = casadi_fmax(w32,w11);
  /* #183: @2 = (@2*@32) */
  w02 *= w32;
  /* #184: @29 = (@29/@2) */
  w29 /= w02;
  /* #185: @28 = (@5*@28) */
  w28  = (w05*w28);
  /* #186: @10 = (@33*@10) */
  w10  = (w33*w10);
  /* #187: @28 = (@28+@10) */
  w28 += w10;
  /* #188: @10 = @31[5] */
  for (rr=(&w10), cs=w31+5; cs!=w31+6; cs+=1) *rr++ = *cs;
  /* #189: @2 = (@9*@29) */
  w02  = (w09*w29);
  /* #190: @2 = (@10-@2) */
  w02  = (w10-w02);
  /* #191: @32 = (@18*@10) */
  w32  = (w18*w10);
  /* #192: @32 = (@33+@32) */
  w32  = (w33+w32);
  /* #193: @19 = fmax(@5,@20) */
  w19  = casadi_fmax(w05,w20);
  /* #194: @32 = atan2(@32,@19) */
  w32  = atan2(w32,w19);
  /* #195: @32 = (@17-@32) */
  w32  = (w17-w32);
  /* #196: @32 = (@16*@32) */
  w32  = (w16*w32);
  /* #197: @32 = atan(@32) */
  w32 = atan( w32 );
  /* #198: @32 = (@15*@32) */
  w32  = (w15*w32);
  /* #199: @32 = sin(@32) */
  w32 = sin( w32 );
  /* #200: @32 = (@14*@32) */
  w32  = (w14*w32);
  /* #201: @3 = (@32*@22) */
  w03  = (w32*w22);
  /* #202: @3 = (@8-@3) */
  w03  = (w08-w03);
  /* #203: @23 = (@24*@33) */
  w23  = (w24*w33);
  /* #204: @23 = (@23*@10) */
  w23 *= w10;
  /* #205: @3 = (@3+@23) */
  w03 += w23;
  /* #206: @3 = (@3/@24) */
  w03 /= w24;
  /* #207: @23 = (@27*@10) */
  w23  = (w27*w10);
  /* #208: @33 = (@33-@23) */
  w33 -= w23;
  /* #209: @33 = atan2(@33,@19) */
  w33  = atan2(w33,w19);
  /* #210: @33 = (@26*@33) */
  w33  = (w26*w33);
  /* #211: @33 = (-@33) */
  w33 = (- w33 );
  /* #212: @33 = atan(@33) */
  w33 = atan( w33 );
  /* #213: @33 = (@15*@33) */
  w33  = (w15*w33);
  /* #214: @33 = sin(@33) */
  w33 = sin( w33 );
  /* #215: @33 = (@25*@33) */
  w33  = (w25*w33);
  /* #216: @19 = (@32*@21) */
  w19  = (w32*w21);
  /* #217: @19 = (@33+@19) */
  w19  = (w33+w19);
  /* #218: @5 = (@24*@5) */
  w05  = (w24*w05);
  /* #219: @5 = (@5*@10) */
  w05 *= w10;
  /* #220: @19 = (@19-@5) */
  w19 -= w05;
  /* #221: @19 = (@19/@24) */
  w19 /= w24;
  /* #222: @32 = (@18*@32) */
  w32  = (w18*w32);
  /* #223: @32 = (@32*@21) */
  w32 *= w21;
  /* #224: @33 = (@27*@33) */
  w33  = (w27*w33);
  /* #225: @32 = (@32-@33) */
  w32 -= w33;
  /* #226: @32 = (@32/@6) */
  w32 /= w06;
  /* #227: @33 = @31[7] */
  for (rr=(&w33), cs=w31+7; cs!=w31+8; cs+=1) *rr++ = *cs;
  /* #228: @33 = (@13-@33) */
  w33  = (w13-w33);
  /* #229: @33 = (@33/@4) */
  w33 /= w04;
  /* #230: @5 = @31[8] */
  for (rr=(&w05), cs=w31+8; cs!=w31+9; cs+=1) *rr++ = *cs;
  /* #231: @5 = (@17-@5) */
  w05  = (w17-w05);
  /* #232: @5 = (@5/@4) */
  w05 /= w04;
  /* #233: @31 = vertcat(@29, @28, @2, @3, @19, @32, @29, @33, @5) */
  rr=w31;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w19;
  *rr++ = w32;
  *rr++ = w29;
  *rr++ = w33;
  *rr++ = w05;
  /* #234: @35 = (2.*@31) */
  for (i=0, rr=w35, cs=w31; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #235: @30 = (@30+@35) */
  for (i=0, rr=w30, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #236: @31 = (@4*@31) */
  for (i=0, rr=w31, cs=w31; i<9; ++i) (*rr++)  = (w04*(*cs++));
  /* #237: @31 = (@0+@31) */
  for (i=0, rr=w31, cr=wr00, cs=w31; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #238: @29 = @31[3] */
  for (rr=(&w29), cs=w31+3; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #239: @28 = @31[2] */
  for (rr=(&w28), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #240: @2 = cos(@28) */
  w02 = cos( w28 );
  /* #241: @3 = (@29*@2) */
  w03  = (w29*w02);
  /* #242: @19 = @31[4] */
  for (rr=(&w19), cs=w31+4; cs!=w31+5; cs+=1) *rr++ = *cs;
  /* #243: @28 = sin(@28) */
  w28 = sin( w28 );
  /* #244: @32 = (@19*@28) */
  w32  = (w19*w28);
  /* #245: @3 = (@3-@32) */
  w03 -= w32;
  /* #246: @32 = @31[1] */
  for (rr=(&w32), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #247: @32 = (@32*@9) */
  w32 *= w09;
  /* #248: @7 = (@7-@32) */
  w07 -= w32;
  /* #249: @32 = sign(@7) */
  w32 = casadi_sign( w07 );
  /* #250: @7 = fabs(@7) */
  w07 = casadi_fabs( w07 );
  /* #251: @7 = fmax(@7,@11) */
  w07  = casadi_fmax(w07,w11);
  /* #252: @32 = (@32*@7) */
  w32 *= w07;
  /* #253: @3 = (@3/@32) */
  w03 /= w32;
  /* #254: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #255: @2 = (@19*@2) */
  w02  = (w19*w02);
  /* #256: @28 = (@28+@2) */
  w28 += w02;
  /* #257: @2 = @31[5] */
  for (rr=(&w02), cs=w31+5; cs!=w31+6; cs+=1) *rr++ = *cs;
  /* #258: @9 = (@9*@3) */
  w09 *= w03;
  /* #259: @9 = (@2-@9) */
  w09  = (w02-w09);
  /* #260: @32 = (@18*@2) */
  w32  = (w18*w02);
  /* #261: @32 = (@19+@32) */
  w32  = (w19+w32);
  /* #262: @20 = fmax(@29,@20) */
  w20  = casadi_fmax(w29,w20);
  /* #263: @32 = atan2(@32,@20) */
  w32  = atan2(w32,w20);
  /* #264: @32 = (@17-@32) */
  w32  = (w17-w32);
  /* #265: @16 = (@16*@32) */
  w16 *= w32;
  /* #266: @16 = atan(@16) */
  w16 = atan( w16 );
  /* #267: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #268: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #269: @14 = (@14*@16) */
  w14 *= w16;
  /* #270: @22 = (@14*@22) */
  w22  = (w14*w22);
  /* #271: @8 = (@8-@22) */
  w08 -= w22;
  /* #272: @22 = (@24*@19) */
  w22  = (w24*w19);
  /* #273: @22 = (@22*@2) */
  w22 *= w02;
  /* #274: @8 = (@8+@22) */
  w08 += w22;
  /* #275: @8 = (@8/@24) */
  w08 /= w24;
  /* #276: @22 = (@27*@2) */
  w22  = (w27*w02);
  /* #277: @19 = (@19-@22) */
  w19 -= w22;
  /* #278: @19 = atan2(@19,@20) */
  w19  = atan2(w19,w20);
  /* #279: @26 = (@26*@19) */
  w26 *= w19;
  /* #280: @26 = (-@26) */
  w26 = (- w26 );
  /* #281: @26 = atan(@26) */
  w26 = atan( w26 );
  /* #282: @15 = (@15*@26) */
  w15 *= w26;
  /* #283: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #284: @25 = (@25*@15) */
  w25 *= w15;
  /* #285: @15 = (@14*@21) */
  w15  = (w14*w21);
  /* #286: @15 = (@25+@15) */
  w15  = (w25+w15);
  /* #287: @29 = (@24*@29) */
  w29  = (w24*w29);
  /* #288: @29 = (@29*@2) */
  w29 *= w02;
  /* #289: @15 = (@15-@29) */
  w15 -= w29;
  /* #290: @15 = (@15/@24) */
  w15 /= w24;
  /* #291: @18 = (@18*@14) */
  w18 *= w14;
  /* #292: @18 = (@18*@21) */
  w18 *= w21;
  /* #293: @27 = (@27*@25) */
  w27 *= w25;
  /* #294: @18 = (@18-@27) */
  w18 -= w27;
  /* #295: @18 = (@18/@6) */
  w18 /= w06;
  /* #296: @6 = @31[7] */
  for (rr=(&w06), cs=w31+7; cs!=w31+8; cs+=1) *rr++ = *cs;
  /* #297: @13 = (@13-@6) */
  w13 -= w06;
  /* #298: @13 = (@13/@4) */
  w13 /= w04;
  /* #299: @6 = @31[8] */
  for (rr=(&w06), cs=w31+8; cs!=w31+9; cs+=1) *rr++ = *cs;
  /* #300: @17 = (@17-@6) */
  w17 -= w06;
  /* #301: @17 = (@17/@4) */
  w17 /= w04;
  /* #302: @31 = vertcat(@3, @28, @9, @8, @15, @18, @3, @13, @17) */
  rr=w31;
  *rr++ = w03;
  *rr++ = w28;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w15;
  *rr++ = w18;
  *rr++ = w03;
  *rr++ = w13;
  *rr++ = w17;
  /* #303: @30 = (@30+@31) */
  for (i=0, rr=w30, cs=w31; i<9; ++i) (*rr++) += (*cs++);
  /* #304: @30 = (@1*@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) (*rr++)  = (w01*(*cs++));
  /* #305: @0 = (@0+@30) */
  for (i=0, rr=w00, cr=wr00, cs=w30; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #306: output[0][0] = @0 */
  casadi_copy(w00, 9, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_mpcc_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 69;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 69*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
