/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[8] = {0, 1, 3, 4, 5, 6, 7, 9};
static const casadi_int casadi_s1[4] = {2, 8, 10, 11};
static const casadi_int casadi_s2[3] = {9, 1, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {1, 1, 1};
static const casadi_int casadi_s7[24] = 
  {11, 9, 0, 1, 3, 4, 5, 6,
  7, 9, 11, 12, 3, 2, 8, 4,
  5, 0, 1, 0, 9, 1, 10, 8};
static const casadi_int casadi_s8[3] = {9, 0, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenth_mpcc_cost_y_0_fun_jac_ut_xt:(i0[9],i1[2],i2[0],i3[],i4)->(o0[9],o1[11x9,12nz],o2[9x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w01, w02, w03, *w04=w+12, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, *w14=w+23, *w15=w+35, *w16=w+43, w17, *w19=w+50, *w20=w+58, *w21=w+61, *w22=w+64, *w23=w+68;
  const casadi_int *cii;
  const casadi_real *cs, *wr00;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[1] */
  w01 = wr00[1];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: @1 = @0[6] */
  w01 = wr00[6];
  /* #4: @2 = @0[0] */
  w02 = wr00[0];
  /* #5: @2 = (@1-@2) */
  w02  = (w01-w02);
  /* #6: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #7: @2 = @0[2] */
  w02 = wr00[2];
  /* #8: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #9: @2 = @0[3] */
  w02 = wr00[3];
  /* #10: @3 = 1.7 */
  w03 = 1.7000000000000000e+00;
  /* #11: @2 = (@2-@3) */
  w02 -= w03;
  /* #12: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #13: @4 = input[1][0] */
  casadi_copy(arg[1], 2, w04);
  /* #14: @2 = @4[0] */
  for (rr=(&w02), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #15: @3 = 0 */
  w03 = 0.;
  /* #16: @5 = fmax(@2,@3) */
  w05  = casadi_fmax(w02,w03);
  /* #17: @6 = 1 */
  w06 = 1.;
  /* #18: @7 = fmin(@5,@6) */
  w07  = casadi_fmin(w05,w06);
  /* #19: output[0][4] = @7 */
  if (res[0]) res[0][4] = w07;
  /* #20: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #21: @9 = -0.35 */
  w09 = -3.4999999999999998e-01;
  /* #22: @10 = fmax(@8,@9) */
  w10  = casadi_fmax(w08,w09);
  /* #23: @11 = 0.35 */
  w11 = 3.4999999999999998e-01;
  /* #24: @12 = fmin(@10,@11) */
  w12  = casadi_fmin(w10,w11);
  /* #25: output[0][5] = @12 */
  if (res[0]) res[0][5] = w12;
  /* #26: @13 = @0[7] */
  w13 = wr00[7];
  /* #27: @7 = (@7-@13) */
  w07 -= w13;
  /* #28: output[0][6] = @7 */
  if (res[0]) res[0][6] = w07;
  /* #29: @7 = @0[8] */
  w07 = wr00[8];
  /* #30: @12 = (@12-@7) */
  w12 -= w07;
  /* #31: output[0][7] = @12 */
  if (res[0]) res[0][7] = w12;
  /* #32: output[0][8] = @1 */
  if (res[0]) res[0][8] = w01;
  /* #33: @14 = zeros(11x9,12nz) */
  casadi_clear(w14, 12);
  /* #34: @15 = ones(11x1,8nz) */
  casadi_fill(w15, 8, 1.);
  /* #35: {@4, @16} = vertsplit(@15) */
  casadi_copy(w15, 2, w04);
  casadi_copy(w15+2, 6, w16);
  /* #36: @1 = @16[1] */
  for (rr=(&w01), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #37: @12 = @16[0] */
  for (rr=(&w12), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #38: @12 = (-@12) */
  w12 = (- w12 );
  /* #39: @7 = @16[2] */
  for (rr=(&w07), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #40: @13 = @16[3] */
  for (rr=(&w13), cs=w16+3; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #41: @17 = (@5<=@6) */
  w17  = (w05<=w06);
  /* #42: @6 = (@6<=@5) */
  w06  = (w06<=w05);
  /* #43: @6 = (@17+@6) */
  w06  = (w17+w06);
  /* #44: @17 = (@17/@6) */
  w17 /= w06;
  /* #45: @6 = (@3<=@2) */
  w06  = (w03<=w02);
  /* #46: @2 = (@2<=@3) */
  w02  = (w02<=w03);
  /* #47: @2 = (@6+@2) */
  w02  = (w06+w02);
  /* #48: @6 = (@6/@2) */
  w06 /= w02;
  /* #49: @2 = @4[0] */
  for (rr=(&w02), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #50: @6 = (@6*@2) */
  w06 *= w02;
  /* #51: @17 = (@17*@6) */
  w17 *= w06;
  /* #52: @6 = (@10<=@11) */
  w06  = (w10<=w11);
  /* #53: @11 = (@11<=@10) */
  w11  = (w11<=w10);
  /* #54: @11 = (@6+@11) */
  w11  = (w06+w11);
  /* #55: @6 = (@6/@11) */
  w06 /= w11;
  /* #56: @11 = (@9<=@8) */
  w11  = (w09<=w08);
  /* #57: @8 = (@8<=@9) */
  w08  = (w08<=w09);
  /* #58: @8 = (@11+@8) */
  w08  = (w11+w08);
  /* #59: @11 = (@11/@8) */
  w11 /= w08;
  /* #60: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #61: @11 = (@11*@8) */
  w11 *= w08;
  /* #62: @6 = (@6*@11) */
  w06 *= w11;
  /* #63: @18 = 00 */
  /* #64: @15 = vertcat(@1, @12, @7, @13, @17, @6, @17, @6, @18) */
  rr=w15;
  *rr++ = w01;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w17;
  *rr++ = w06;
  *rr++ = w17;
  *rr++ = w06;
  /* #65: @19 = @15[:8] */
  for (rr=w19, cs=w15+0; cs!=w15+8; cs+=1) *rr++ = *cs;
  /* #66: (@14[0, 1, 3, 4, 5, 6, 7, 9] = @19) */
  for (cii=casadi_s0, rr=w14, cs=w19; cii!=casadi_s0+8; ++cii, ++cs) rr[*cii] = *cs;
  /* #67: @20 = ones(11x1,3nz) */
  casadi_fill(w20, 3, 1.);
  /* #68: {NULL, @21} = vertsplit(@20) */
  casadi_copy(w20, 3, w21);
  /* #69: @1 = @21[0] */
  for (rr=(&w01), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #70: @12 = @21[1] */
  for (rr=(&w12), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #71: @12 = (-@12) */
  w12 = (- w12 );
  /* #72: @7 = @21[2] */
  for (rr=(&w07), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #73: @7 = (-@7) */
  w07 = (- w07 );
  /* #74: @22 = vertcat(@18, @1, @18, @18, @18, @18, @12, @7, @1) */
  rr=w22;
  *rr++ = w01;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w01;
  /* #75: @23 = @22[:4] */
  for (rr=w23, cs=w22+0; cs!=w22+4; cs+=1) *rr++ = *cs;
  /* #76: (@14[2, 8, 10, 11] = @23) */
  for (cii=casadi_s1, rr=w14, cs=w23; cii!=casadi_s1+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #77: output[1][0] = @14 */
  casadi_copy(w14, 12, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 72;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 72*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
