/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_mpcc_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenth_mpcc_cost_y_fun:(i0[9],i1[2],i2[0],i3[],i4)->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w1, w2, w3, *w4=w+12, w5;
  const casadi_real *cs, *wr0;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[1] */
  w1 = wr0[1];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[6] */
  w1 = wr0[6];
  /* #4: @2 = @0[0] */
  w2 = wr0[0];
  /* #5: @2 = (@1-@2) */
  w2  = (w1-w2);
  /* #6: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #7: @2 = @0[2] */
  w2 = wr0[2];
  /* #8: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #9: @2 = @0[3] */
  w2 = wr0[3];
  /* #10: @3 = 1.7 */
  w3 = 1.7000000000000000e+00;
  /* #11: @2 = (@2-@3) */
  w2 -= w3;
  /* #12: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #13: @4 = input[1][0] */
  casadi_copy(arg[1], 2, w4);
  /* #14: @2 = @4[0] */
  for (rr=(&w2), cs=w4+0; cs!=w4+1; cs+=1) *rr++ = *cs;
  /* #15: @3 = 0 */
  w3 = 0.;
  /* #16: @2 = fmax(@2,@3) */
  w2  = casadi_fmax(w2,w3);
  /* #17: @3 = 1 */
  w3 = 1.;
  /* #18: @2 = fmin(@2,@3) */
  w2  = casadi_fmin(w2,w3);
  /* #19: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #20: @3 = @4[1] */
  for (rr=(&w3), cs=w4+1; cs!=w4+2; cs+=1) *rr++ = *cs;
  /* #21: @5 = -0.35 */
  w5 = -3.4999999999999998e-01;
  /* #22: @3 = fmax(@3,@5) */
  w3  = casadi_fmax(w3,w5);
  /* #23: @5 = 0.35 */
  w5 = 3.4999999999999998e-01;
  /* #24: @3 = fmin(@3,@5) */
  w3  = casadi_fmin(w3,w5);
  /* #25: output[0][5] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #26: @5 = @0[7] */
  w5 = wr0[7];
  /* #27: @2 = (@2-@5) */
  w2 -= w5;
  /* #28: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #29: @2 = @0[8] */
  w2 = wr0[8];
  /* #30: @3 = (@3-@2) */
  w3 -= w2;
  /* #31: output[0][7] = @3 */
  if (res[0]) res[0][7] = w3;
  /* #32: output[0][8] = @1 */
  if (res[0]) res[0][8] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_mpcc_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 15*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
