/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[14] = 
  {9, 5, 0, 1, 3, 4, 5, 6,
  1, 0, 6, 2, 3, 6};
static const casadi_int casadi_s6[3] = {5, 0, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenth_mpcc_cost_y_e_fun_jac_ut_xt:(i0[9],i1[0],i2[0],i3[],i4)->(o0[5],o1[9x5,6nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *tt, w1, w2, w3, *w4=w+12, *w6=w+18, *w7=w+22, *w8=w+26, *w9=w+28;
  const casadi_real *cs, *wr0;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[1] */
  w1 = wr0[1];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[6] */
  w1 = wr0[6];
  /* #4: @2 = @0[0] */
  w2 = wr0[0];
  /* #5: @2 = (@1-@2) */
  w2  = (w1-w2);
  /* #6: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #7: @2 = @0[2] */
  w2 = wr0[2];
  /* #8: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #9: @2 = @0[3] */
  w2 = wr0[3];
  /* #10: @3 = 1.7 */
  w3 = 1.7000000000000000e+00;
  /* #11: @2 = (@2-@3) */
  w2 -= w3;
  /* #12: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #13: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #14: @4 = zeros(9x5,6nz) */
  casadi_clear(w4, 6);
  /* #15: @1 = 1 */
  w1 = 1.;
  /* #16: @2 = -1 */
  w2 = -1.;
  /* #17: @5 = 00 */
  /* #18: @6 = vertcat(@1, @2, @1, @1, @5) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w1;
  /* #19: @7 = @6[:4] */
  for (rr=w7, cs=w6+0; cs!=w6+4; cs+=1) *rr++ = *cs;
  /* #20: (@4[:6:3;:2] = @7) */
  for (rr=w4+0, cs=w7; rr!=w4+6; rr+=3) for (tt=rr+0; tt!=rr+2; tt+=1) *tt = *cs++;
  /* #21: @8 = vertcat(@5, @1, @5, @5, @1) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w1;
  /* #22: @9 = @8[:2] */
  for (rr=w9, cs=w8+0; cs!=w8+2; cs+=1) *rr++ = *cs;
  /* #23: (@4[2:8:3] = @9) */
  for (rr=w4+2, cs=w9; rr!=w4+8; rr+=3) *rr = *cs++;
  /* #24: output[1][0] = @4 */
  casadi_copy(w4, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 30;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_mpcc_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 30*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
