/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_frenet_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[13] = 
  {8, 5, 0, 1, 2, 3, 4, 5,
  3, 4, 5, 0, 1};
static const casadi_int casadi_s7[3] = {5, 0, 1};

/* f1tenth_frenet_cost_y_fun_jac_ut_xt:(i0[6],i1[2],i2[0],i3[],i4)->(o0[5],o1[8x5,5nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, w1, w2, *w3=w+8, *w4=w+10, *w5=w+15, w6, w7, w8, *w9=w+26;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = @0[1] */
  for (rr=(&w1), cs=w0+1; cs!=w0+2; cs+=1) *rr++ = *cs;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[2] */
  for (rr=(&w1), cs=w0+2; cs!=w0+3; cs+=1) *rr++ = *cs;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[3] */
  for (rr=(&w1), cs=w0+3; cs!=w0+4; cs+=1) *rr++ = *cs;
  /* #6: @2 = 2.5 */
  w2 = 2.5000000000000000e+00;
  /* #7: @1 = (@1-@2) */
  w1 -= w2;
  /* #8: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #9: @3 = input[1][0] */
  casadi_copy(arg[1], 2, w3);
  /* #10: @1 = @3[0] */
  for (rr=(&w1), cs=w3+0; cs!=w3+1; cs+=1) *rr++ = *cs;
  /* #11: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #12: @1 = @3[1] */
  for (rr=(&w1), cs=w3+1; cs!=w3+2; cs+=1) *rr++ = *cs;
  /* #13: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #14: @4 = zeros(8x5,5nz) */
  casadi_clear(w4, 5);
  /* #15: @5 = ones(8x1) */
  casadi_fill(w5, 8, 1.);
  /* #16: {@3, @0} = vertsplit(@5) */
  casadi_copy(w5, 2, w3);
  casadi_copy(w5+2, 6, w0);
  /* #17: @1 = @0[1] */
  for (rr=(&w1), cs=w0+1; cs!=w0+2; cs+=1) *rr++ = *cs;
  /* #18: @2 = @0[2] */
  for (rr=(&w2), cs=w0+2; cs!=w0+3; cs+=1) *rr++ = *cs;
  /* #19: @6 = @0[3] */
  for (rr=(&w6), cs=w0+3; cs!=w0+4; cs+=1) *rr++ = *cs;
  /* #20: @7 = @3[0] */
  for (rr=(&w7), cs=w3+0; cs!=w3+1; cs+=1) *rr++ = *cs;
  /* #21: @8 = @3[1] */
  for (rr=(&w8), cs=w3+1; cs!=w3+2; cs+=1) *rr++ = *cs;
  /* #22: @9 = vertcat(@1, @2, @6, @7, @8) */
  rr=w9;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #23: (@4[:5] = @9) */
  for (rr=w4+0, cs=w9; rr!=w4+5; rr+=1) *rr = *cs++;
  /* #24: output[1][0] = @4 */
  casadi_copy(w4, 5, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_frenet_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_frenet_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_frenet_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_frenet_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_frenet_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 31;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_frenet_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 31*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
